-- Non-secret production card content snapshot, 2026-09-17.
-- Intentionally excludes rooms, players, submissions, tokens and app_settings.

insert into public.questions(id, text) overriding system value values
(1, 'Ce soir, au lieu de dormir, je vais ____.'),
(2, 'Le secret de ma grand-mère pour rester en forme : ____.'),
(3, 'Nouveau meuble en kit : ____, à monter soi-même.'),
(4, 'J''ai été viré de la chorale à cause de ____.'),
(5, 'Le prochain sport olympique : ____.'),
(6, 'Ce qui ne devrait jamais figurer sur un CV : ____.'),
(7, 'Mon psy m''a conseillé d''arrêter ____.'),
(8, 'Dans mon prochain tatouage, il y aura ____.'),
(9, 'La vraie raison de la disparition des dinosaures : ____.'),
(10, 'Au mariage de mon cousin, tout le monde se souvient surtout de ____.'),
(11, 'Nouveau parfum de chips : ____.'),
(12, 'Ma mère m''a surpris avec ____.'),
(13, 'Le Wi-Fi de l''hôtel s''appelle « ____ ».'),
(14, 'Ce qui se cache vraiment au fond de mon frigo : ____.'),
(15, 'Pour mon anniversaire, je veux juste ____.'),
(16, 'Mon premier rencard s''est terminé à cause de ____.'),
(17, 'Le nouveau jeu télé du samedi soir : « Qui veut gagner ____ ? »'),
(18, 'Selon mon horoscope, cette semaine sera marquée par ____.'),
(19, 'La devise de notre famille : « ____ ».'),
(20, 'Ce que mon chat pense vraiment de moi : ____.'),
(21, 'Au Moyen Âge, on soignait tout avec ____.'),
(22, 'Mon voisin fait un bruit bizarre la nuit. Je pense que c''est ____.'),
(23, 'Le guide touristique déconseille formellement ____.'),
(24, 'Mon dernier achat en ligne à 3 h du matin : ____.'),
(25, 'Le thème de la soirée d''entreprise : ____.'),
(26, 'J''ai dû expliquer ____ à la douane.'),
(27, 'Ce qui a vraiment inspiré la Joconde : ____.'),
(28, 'Réunion parents-profs : « Votre enfant est obsédé par ____. »'),
(29, 'Il paraît que le bonheur, c''est ____.'),
(30, 'Le nouveau cours à la salle de sport : ____ pour débutants.'),
(31, 'Pourquoi j''ai été banni du camping ? ____.'),
(32, 'Le seul souvenir que je rapporte de vacances : ____.'),
(33, 'Nouvelle appli de rencontre, réservée aux fans de ____.'),
(34, 'Mon GPS m''a dit de tourner à droite, et je suis tombé sur ____.'),
(35, 'Le vrai contenu du coffre-fort de la Banque de France : ____.'),
(36, 'Ma résolution pour l''an prochain : moins de ____.'),
(37, 'Le dernier message de mon ex : « Rends-moi ____. »'),
(38, 'Aux Jeux olympiques de la flemme, la médaille d''or revient à ____.'),
(39, 'Mon talent caché : ____.'),
(40, 'Dans la lettre au père Noël de mon neveu : ____.'),
(41, 'Ce qu''on trouve toujours au fond d''un sac à main : ____.'),
(42, 'Nouvelle attraction au parc : le grand huit de ____.'),
(43, 'Sujet de philo : « Peut-on rire de ____ ? »'),
(44, 'J''ai raté mon permis à cause de ____.'),
(45, 'L''odeur étrange dans la voiture ? C''est ____.'),
(46, 'Cette année, le comité d''entreprise offre ____.'),
(47, 'La meilleure façon de rompre : ____.'),
(48, 'Mon coloc a laissé un mot : « Merci de ranger ____. »'),
(49, 'Le nouveau best-seller : « Réussir sa vie grâce à ____ ».'),
(50, 'Pendant le confinement, je me suis mis à ____.'),
(51, 'Les extraterrestres ne nous contactent pas à cause de ____.'),
(52, 'Le dessert du chef : une mousse de ____.'),
(53, 'À la fin du repas de famille, ça finit toujours par parler de ____.'),
(54, '____ : la nouvelle drogue des retraités.'),
(55, 'Ce que je murmure à mes plantes : ____.'),
(56, 'L''invention qui va tout changer : ____.'),
(57, 'Le vigile m''a arrêté à la sortie parce que j''avais ____.'),
(58, 'Ma photo de profil montre ____.'),
(59, 'Le prochain scandale à la mairie : ____.'),
(60, 'Mon plan retraite repose entièrement sur ____.'),
(61, 'Le pire truc à sortir pendant un enterrement : ____.'),
(62, '« Docteur, j''ai un problème avec ____. »'),
(63, 'Le nouveau goût de dentifrice : ____.'),
(64, 'Mon oncle raconte toujours la même histoire : celle de ____.'),
(65, '____ : c''est comme le vélo, ça ne s''oublie pas.'),
(66, 'J''ai dépensé tout mon héritage dans ____.'),
(67, 'Le sujet du bac cette année : ____.'),
(68, 'La météo annonce des averses de ____.'),
(69, 'Le plus gros mensonge de mon enfance : ____.'),
(70, 'À l''entretien d''embauche, j''ai parlé de ____. Grosse erreur.'),
(71, 'Ce qui rend une soirée pyjama inoubliable : ____.'),
(72, 'Le nom de mon futur groupe de rock : ____.'),
(73, 'Les voisins organisent une fête sur le thème : ____.'),
(74, 'La police a retrouvé ____ dans la boîte à gants.'),
(75, 'Pour séduire, rien ne vaut ____.'),
(76, 'Le sommelier recommande ____ avec le fromage.'),
(77, 'Mon rêve de cette nuit : ____ et moi sur une île déserte.'),
(78, 'Après trois verres, mon père ne parle plus que de ____.'),
(79, 'Le secret de la longévité des Français : ____.'),
(80, 'Le club de lecture de ma tante est en réalité un club de ____.'),
(81, 'La maîtresse a convoqué mes parents à cause de ____.'),
(82, 'Ce que je cherche en vain sur Internet : ____.'),
(83, 'En cas d''apocalypse, j''emporte ____.'),
(84, '____ : ça sent bon, mais c''est interdit.'),
(85, 'Le prochain film catastrophe : « L''attaque de ____ ».'),
(86, 'Mon dernier Uber s''est terminé avec ____.'),
(87, 'Ce que j''ai trouvé en rentrant de week-end : ____.'),
(88, 'Nouveau stage de développement personnel : « Libérez votre ____ intérieur ».'),
(89, 'Le cadeau le plus gênant de Noël : ____.'),
(90, 'Ce qui m''a valu un mois de privation de dessert : ____.'),
(93, 'Ce que je regrette le plus de ma soirée d''hier : ____.'),
(94, 'Mon mot de sécurité : « ____ ».'),
(95, 'Le secret d''une nuit réussie : ____.'),
(96, 'Ce que j''ai trouvé dans la table de nuit de mes parents : ____.'),
(97, 'Au lit, j''ai une seule exigence : ____.'),
(98, 'Mon ex m''a quitté à cause de ____.'),
(99, 'Le nouveau jouet pour adultes : ____.'),
(100, 'Ce que je fais quand mes colocs ne sont pas là : ____.'),
(101, 'Ma bio sur l''appli de rencontre : « Fan de ____. »'),
(102, 'Ce qui m''a valu une nuit au poste : ____.'),
(103, 'Mon premier baiser avait un goût de ____.'),
(104, 'Le thème de l''enterrement de vie de garçon : ____.'),
(105, 'Après la fête, on a retrouvé ____ dans la baignoire.'),
(106, 'Ce que je ne dirai jamais à mon médecin : ____.'),
(107, 'Ma technique de drague infaillible : ____.'),
(108, 'La honte du réveillon : ____.'),
(109, 'Ce que l''alcootest a vraiment détecté : ____.'),
(110, 'Le titre de ma sextape : « ____ ».'),
(111, 'Pour pimenter notre couple, on a essayé ____.'),
(112, 'Mon plus gros fantasme : ____.'),
(113, 'Ce qui s''est passé à Ibiza reste à Ibiza, sauf ____.'),
(114, 'Le message que je n''aurais jamais dû envoyer à mon patron : « ____ ».'),
(115, 'La vraie raison de mon arrêt maladie : ____.'),
(116, 'Dans l''historique de mon téléphone, on trouve surtout ____.'),
(117, 'Au spa, j''ai été viré pour ____.'),
(118, 'Le cadeau parfait pour une première nuit : ____.'),
(119, 'Le programme de l''enterrement de vie de jeune fille : ____.'),
(120, 'Ce que les voisins ont entendu cette nuit : ____.'),
(121, 'Le nouveau cocktail du bar : ____ on the beach.'),
(122, 'Le lendemain de soirée, je me suis réveillé avec ____.'),
(123, 'L''arbitre a sifflé penalty à cause de ____.'),
(124, 'Le nouveau chant des supporters : « ____ ! »'),
(125, 'La VAR a revu l''action et a découvert ____.'),
(126, 'Le coach a été viré pour ____.'),
(127, 'Au mercato, mon club a recruté ____.'),
(128, 'Pour motiver l''équipe à la mi-temps, le coach a sorti ____.'),
(129, 'Le vrai contenu de la gourde de l''entraîneur : ____.'),
(130, 'Carton rouge direct pour ____.'),
(131, 'Le nouveau sponsor sur le maillot : ____.'),
(132, 'Au foot à cinq du jeudi, on se dispute toujours pour ____.'),
(133, 'Le secret de ma célébration de but : ____.'),
(134, 'Pendant le match, un supporter a lancé ____ sur la pelouse.'),
(135, 'La tactique secrète du coach : ____.'),
(136, 'Dans le vestiaire, ça sent ____.'),
(137, 'Mon club de district a été racheté par ____.')
on conflict (id) do update set text=excluded.text, added_by=null, deleted_at=null;

select setval(pg_get_serial_sequence('public.questions','id'), (select max(id) from public.questions), true);

insert into public.answers(id, text) overriding system value values
(1, 'Un pigeon qui a vu trop de choses'),
(2, 'Ma belle-mère en maillot de bain'),
(3, 'Un karaoké de six heures'),
(4, 'Des chaussettes dans des sandales'),
(5, 'Le slip de mon grand-père'),
(6, 'Une raclette en plein mois d''août'),
(7, 'Un compte Instagram pour mon hamster'),
(8, 'Trois kilos de fromage fondu'),
(9, 'La honte de toute la famille'),
(10, 'Un poney dépressif'),
(11, 'Des mains moites'),
(12, 'Le groupe WhatsApp de la famille'),
(13, 'Une danse du ventre ratée'),
(14, 'Un moustachu très sûr de lui'),
(15, 'L''odeur du métro en juillet'),
(16, 'Un sèche-cheveux qui sent le brûlé'),
(17, 'Des pieds qui sentent le camembert'),
(18, 'Mon historique de navigation'),
(19, 'Un rot de douze secondes'),
(20, 'Une crise existentielle au rayon surgelés'),
(21, 'Un nain de jardin possédé'),
(22, 'Un tonton qui a trop bu'),
(23, 'Un stagiaire non rémunéré'),
(24, 'Un gigot entier dans mon sac'),
(25, 'Des photos de vacances de 2009'),
(26, 'Un poisson rouge qui juge tout le monde'),
(27, 'Un sosie de moi, en plus beau'),
(28, 'Des flatulences mal maîtrisées'),
(29, 'Un clown triste'),
(30, 'Un tiroir plein de sachets de sauce soja'),
(31, 'La chanson de l''été, en boucle'),
(32, 'Une perruque en poils de chat'),
(33, 'Un câlin qui dure beaucoup trop longtemps'),
(34, 'Mon ex déguisé en licorne'),
(35, 'Une moustache dessinée au feutre'),
(36, 'Un régime 100 % pâte à tartiner'),
(37, 'Un colis perdu depuis 2017'),
(38, 'Une chèvre qui parle anglais'),
(39, 'Des lunettes de soleil en pleine nuit'),
(40, 'Un appel de mon banquier'),
(41, 'Le prof de sport en short moulant'),
(42, 'Un sachet de mayonnaise tiède'),
(43, 'Un mariage express à Las Vegas'),
(44, 'Un rendez-vous chez le proctologue'),
(45, 'Un pet dans l''ascenseur'),
(46, 'Ma collection de nains de jardin'),
(47, 'Des chips au goût de pied'),
(48, 'Une soirée diapos chez tonton'),
(49, 'Un canapé qui a trop vécu'),
(50, 'Le chauffeur de bus qui chante'),
(51, 'Des cris de loutre'),
(52, 'Une pédicure ratée'),
(53, 'Des poils de nez géants'),
(54, 'Un poulet rôti caché dans mon manteau'),
(55, 'Une tente qui refuse de se replier'),
(56, 'Mon compte en banque dans le rouge'),
(57, 'Un DJ de mariage en roue libre'),
(58, 'Un bébé qui juge tout le monde'),
(59, 'Des sous-vêtements comestibles'),
(60, 'Un massage aux huiles douteuses'),
(61, 'Un speed dating chez les retraités'),
(62, 'Des dents en or'),
(63, 'Une barbe pleine de miettes'),
(64, 'Le vide intersidéral de mon frigo'),
(65, 'Une vidéo de danse de ma grand-mère'),
(66, 'Une gueule de bois de trois jours'),
(67, 'Un plan foireux'),
(68, 'Un escargot en cavale'),
(69, 'Des chaussures qui couinent'),
(70, 'Un mime agressif'),
(71, 'Un sandwich de la veille'),
(72, 'Une sieste de quatorze heures'),
(73, 'L''amour, le vrai'),
(74, 'Les impôts'),
(75, 'Un string léopard'),
(76, 'Un string oublié chez les voisins'),
(77, 'Un lama en colère'),
(78, 'Une crème antirides pour les pieds'),
(79, 'Mes parents qui s''embrassent'),
(80, 'Un cri primal au supermarché'),
(81, 'Un tupperware jamais rendu'),
(82, 'Des bisous baveux'),
(83, 'Un bob de camping'),
(84, 'Un apéro qui dégénère'),
(85, 'Un tracteur volé'),
(86, 'Une fondue savoyarde par 40 degrés'),
(87, 'Un cheveu dans la soupe'),
(88, 'Un calendrier des pompiers'),
(89, 'Mon propre reflet'),
(90, 'Une piscine à balles pour adultes'),
(91, 'Un chihuahua enragé'),
(92, 'L''hymne national au kazoo'),
(93, 'Un slam sur la choucroute'),
(94, 'Une invasion de mouettes'),
(95, 'Un ticket de loto gagnant passé à la machine'),
(96, 'Une grosse gifle'),
(97, 'Le silence gênant après une blague'),
(98, 'Une cravate en jambon'),
(99, 'Un lapin nain très ambitieux'),
(100, 'Une ceinture de chasteté'),
(101, 'Le petit orteil'),
(102, 'Une piqûre de moustique mal placée'),
(103, 'Des bouchons d''oreilles usagés'),
(104, 'Un stage de tantra'),
(105, 'Le chèque de mamie'),
(106, 'Un cousin qui fait de la crypto'),
(107, 'Des bougies parfumées au bacon'),
(108, 'Un bébé phoque'),
(109, 'Un tonneau de vin rouge'),
(110, 'Des tongs dans la neige'),
(111, 'Le sens du rouleau de papier toilette'),
(112, 'Du papier toilette triple épaisseur'),
(113, 'Le yoga du rire'),
(114, 'Une coupe mulet'),
(115, 'Des aisselles qui dégoulinent'),
(116, 'Un vieux kebab'),
(117, 'Un jacuzzi tiède'),
(118, 'Un permis avec zéro point'),
(119, 'Une prise de sang'),
(120, 'Un cafard qui connaît mon prénom'),
(121, 'Un anniversaire surprise raté'),
(122, 'La crise de la quarantaine'),
(123, 'Un marathon en pantoufles'),
(124, 'De l''harmonica à 7 heures du matin'),
(125, 'Un voisin nudiste'),
(126, 'Des fesses bien fermes'),
(127, 'Un bisou sur le front'),
(128, 'Des fesses coincées dans une bouée'),
(129, 'Le contrôle fiscal'),
(130, 'Une omelette aux chaussettes'),
(131, 'Une momie en colère'),
(132, 'Une licorne en fin de carrière'),
(133, 'Un papi qui twerke'),
(134, 'Des dents de lapin'),
(135, 'Une soupe au chou'),
(136, 'Le démon de minuit'),
(137, 'Un gratin de pâtes à 2 heures du matin'),
(138, 'Une compilation de vidéos de chats'),
(139, 'Une prise électrique qui fume'),
(140, 'Un blind test de musiques d''ascenseur'),
(141, 'Une chaise de jardin en plastique'),
(142, 'Un couple qui se dispute au rayon cuisines'),
(143, 'Mes bulletins de notes du lycée'),
(144, 'Un poster géant de moi-même'),
(145, 'Un type qui explique la vie à tout le monde'),
(146, 'Une tante qui veut absolument me caser'),
(147, 'Une remarque sur ma coupe de cheveux'),
(148, 'Un moine qui fait du skate'),
(149, 'Un faux accent italien'),
(150, 'Un jeu de mots pourri'),
(151, 'Un cornichon géant'),
(152, 'Une aubergine suggestive'),
(153, 'Un concombre de 40 centimètres'),
(154, 'Mes plantes mortes'),
(155, 'Un soutien-gorge accroché au lustre'),
(156, 'Des crêpes au ketchup'),
(157, 'Un bateau gonflable percé'),
(158, 'Des sandales à scratch'),
(159, 'Une part de pizza retrouvée sous le lit'),
(160, 'Un lama qui crache'),
(161, 'Un préservatif périmé'),
(162, 'Un test de grossesse'),
(163, 'Un pot de rillettes'),
(164, 'Un rap sur la fiscalité'),
(165, 'Un chanteur de charme en tournée d''adieu'),
(166, 'Une vieille cassette VHS louche'),
(167, 'Un dentier dans un verre d''eau'),
(168, 'Mon ex et son nouveau mec'),
(169, 'Une soirée mousse'),
(170, 'Une moule pas fraîche'),
(171, 'Un pull de Noël qui clignote'),
(172, 'Un tapis de course qui sert de portemanteau'),
(173, 'Un pigeon voyageur perdu'),
(174, 'Des gaufres au maroilles'),
(175, 'Un gourou du bien-être'),
(176, 'Un cercle de tambours'),
(177, 'Une battle de danse avec mon père'),
(178, 'Un grille-pain possédé'),
(179, 'Un robot aspirateur qui a des sentiments'),
(180, 'Une chanson d''amour pour ma voiture'),
(181, 'Un selfie aux toilettes'),
(182, 'Une fessée'),
(183, 'Un dîner aux chandelles avec ma mère'),
(184, 'Un club de strip-tease pour seniors'),
(185, 'Des lingettes pour bébé'),
(186, 'Un coup de soleil en forme de maillot'),
(187, 'Un orteil en trop'),
(188, 'Un chapeau de cow-boy'),
(189, 'Un saucisson de deux mètres'),
(190, 'Une révolte de hamsters'),
(191, 'Un monocle'),
(192, 'Mon patron en maillot de bain'),
(193, 'Une cabine d''essayage occupée depuis trois heures'),
(194, 'Un plombier très bavard'),
(195, 'Une vidéo compromettante'),
(196, 'Des menottes en fourrure'),
(197, 'La pizza à l''ananas'),
(198, 'Des nuggets au petit-déjeuner'),
(199, 'Un ours en peluche traumatisé'),
(200, 'Un sachet de thé réutilisé douze fois'),
(201, 'Un voisin qui tond sa pelouse le dimanche'),
(202, 'Un vieux chewing-gum collé sous la table'),
(203, 'Un accordéon'),
(204, 'Un tuto maquillage raté'),
(205, 'Des larmes de joie'),
(206, 'Une chèvre qui hurle'),
(207, 'Le pouvoir de l''amitié'),
(208, 'Une addiction au fromage'),
(209, 'Un GPS qui parle en alexandrins'),
(210, 'Un taxidermiste passionné'),
(211, 'Un dauphin qui se moque de moi'),
(212, 'Un fan-club de la TVA'),
(213, 'Un chien à lunettes'),
(214, 'Du beurre salé, beaucoup'),
(215, 'Une verrue sur le menton'),
(216, 'Des cuisses de grenouille'),
(217, 'Une claquette dans la figure'),
(218, 'Un apéro en visio'),
(219, 'Un petit pipi dans la piscine'),
(220, 'Une crotte de nez'),
(221, 'Un hérisson dans le slip'),
(222, 'Mon compte secret sur les réseaux'),
(223, 'Des sous-titres en allemand'),
(224, 'Une dispute de couple au Scrabble'),
(225, 'Un pyjama en pilou-pilou'),
(226, 'Un compliment bizarre'),
(227, 'Un squelette dans le placard'),
(228, 'Une douche froide'),
(229, 'La retraite à 90 ans'),
(230, 'Un poulpe amoureux'),
(231, 'Un ongle incarné'),
(232, 'Des mollets en béton'),
(233, 'Un escape game dont on ne sort jamais'),
(234, 'Des ballons en forme de zizi'),
(235, 'La pinte de trop'),
(236, 'Le repas de Noël'),
(237, 'Un pantalon beaucoup trop serré'),
(238, 'Un bisou esquimau'),
(239, 'Un réveil qui sonne à 4 h 30'),
(240, 'Des pâtes sans sel'),
(241, 'Le cours d''éducation sexuelle'),
(242, 'Mon corps de rêve (en construction)'),
(243, 'Un tamagotchi mort'),
(244, 'Un voyage organisé en car'),
(245, 'Une chorale de mamies déchaînées'),
(246, 'Un pédalo en pleine tempête'),
(247, 'Un mot de passe écrit sur un Post-it'),
(248, 'Des fausses dents de vampire'),
(249, 'Une cave à vin vide'),
(250, 'Un doudou qui sent très fort'),
(251, 'Une trottinette électrique dans le canal'),
(252, 'Un bisou volé'),
(253, 'Une cagnotte pour mon divorce'),
(254, 'Un magicien qui rate tous ses tours'),
(255, 'Un cochon d''Inde en tutu'),
(259, 'Un plan à trois qui tourne mal'),
(260, 'Des menottes sans la clé'),
(261, 'Une gueule de bois monumentale'),
(262, 'Un tonton en string'),
(263, 'Des préliminaires de trois secondes'),
(264, 'Des photos que maman n''aurait pas dû voir'),
(265, 'Un vibromasseur en mode turbo'),
(266, 'Du lubrifiant goût barbecue'),
(267, 'Une panne au pire moment'),
(268, 'Mon ex à 3 heures du matin'),
(269, 'Un vocal de douze minutes envoyé bourré'),
(270, 'Un vomi dans le taxi'),
(271, 'Un strip-tease raté'),
(272, 'Des chaussettes gardées pendant l''acte'),
(273, 'Le plan cul de ma coloc'),
(274, 'Un suçon sur le front'),
(275, 'Une capote trouée'),
(276, 'Un réveil à côté d''un inconnu'),
(277, 'Une nuit torride au camping'),
(278, 'Le kamasutra version retraités'),
(279, 'Une combinaison en latex'),
(280, 'Un gage qui va beaucoup trop loin'),
(281, 'Un rencard avec ma prof de yoga'),
(282, 'Un fouet en plastique'),
(283, 'Un tabouret de bar et beaucoup de courage'),
(284, 'Une érection en pleine réunion'),
(285, 'Un pet pendant les préliminaires'),
(286, 'Une épilation du maillot ratée'),
(287, 'Le shot de tequila de trop'),
(288, 'Un karaoké torse nu'),
(289, 'Un after chez un inconnu'),
(290, 'Des fesses sur la photocopieuse'),
(291, 'Des draps à brûler'),
(292, 'Un cri de plaisir un peu trop fort'),
(293, 'Les voisins qui tapent au mur'),
(294, 'Une nuit blanche, et pas pour réviser'),
(295, 'Un test de dépistage'),
(296, 'Une danse lascive sur le capot'),
(297, 'Un nude envoyé au groupe de la famille'),
(298, 'Une mycose tenace'),
(299, 'Des boules de geisha'),
(300, 'Un tanga fluo'),
(301, 'Une partie de jambes en l''air ratée'),
(302, 'Un ex qui revient toujours'),
(303, 'Une bouteille de rhum premier prix'),
(304, 'Un vomi sur les chaussures de la mariée'),
(305, 'Une nuit en cellule de dégrisement'),
(306, 'Un massage qui finit bizarrement'),
(307, 'Un porte-jarretelles'),
(308, 'Une sextape floue'),
(309, 'Une dispute pour savoir qui a ronflé'),
(310, 'Le fantasme du plombier'),
(311, 'Un costume d''infirmière coquine'),
(312, 'Un préservatif à la fraise'),
(313, 'Une cuite au mousseux'),
(314, 'Des aveux sous l''effet du rosé'),
(315, 'Un ex qui like toutes mes photos'),
(316, 'Un furoncle sur la fesse'),
(317, 'Une libido en berne'),
(318, 'Un sex-toy qui parle'),
(319, 'Une nuit dans un jacuzzi public'),
(320, 'Des sous-vêtements retrouvés dans le sapin'),
(321, 'Un slow collé-serré avec le DJ'),
(322, 'Un tatouage sur la fesse gauche'),
(323, 'Un réveil dans la mauvaise ville'),
(324, 'Un penalty imaginaire'),
(325, 'Un tacle à la gorge'),
(326, 'La VAR en panne'),
(327, 'Un arbitre payé en merguez'),
(328, 'Un coup franc en pleine lucarne'),
(329, 'Un plongeon digne des JO'),
(330, 'Un 0-0 de 90 minutes'),
(331, 'Un supporter torse nu en décembre'),
(332, 'Des protège-tibias en carton'),
(333, 'Un but contre son camp à la 93e'),
(334, 'Un remplaçant qui s''échauffe depuis trois ans'),
(335, 'Le mercato d''hiver'),
(336, 'Une célébration torse nu'),
(337, 'Un fumigène en tribune'),
(338, 'Un maillot floqué à mon nom'),
(339, 'Un coup de crampon dans le mollet'),
(340, 'Un hors-jeu d''un orteil'),
(341, 'Une frappe dans les tribunes'),
(342, 'Un coach qui mâche du chewing-gum'),
(343, 'Un gardien de 120 kilos'),
(344, 'Un match de district sous la pluie'),
(345, 'Une passe décisive pour l''adversaire'),
(346, 'Des chaussettes de foot qui puent'),
(347, 'Un arbitre qui ne court jamais'),
(348, 'Une simulation de blessure'),
(349, 'Un carton rouge à la 2e minute'),
(350, 'Un kop qui chante faux'),
(351, 'L''odeur du camphre'),
(352, 'Un ballon crevé'),
(353, 'Une tête plongeante dans la boue'),
(354, 'Une bagarre générale pour un corner'),
(355, 'Un entraîneur en survêtement depuis 1998')
on conflict (id) do update set text=excluded.text, added_by=null, deleted_at=null;

select setval(pg_get_serial_sequence('public.answers','id'), (select max(id) from public.answers), true);
