-- Non-secret production card content snapshot, 2026-09-17.
-- Intentionally excludes rooms, players, submissions, tokens and app_settings.

insert into public.questions(id, text) overriding system value values
(1, 'Ce soir, au lieu de dormir, je vais ____.'),
(2, 'Le secret de ma grand-mère pour rester en forme : ____.'),
(3, 'Nouveau meuble en kit : ____, à monter soi-même.'),
(4, 'J''ai été viré de la chorale à cause de ____.'),
(5, 'Le prochain sport olympique : ____.'),
(6, 'Ce qui ne devrait jamais figurer sur un CV : ____.'),
(7, 'Mon psy m''a conseillé d''arrêter ____.'),
(8, 'Dans mon prochain tatouage, il y aura ____.'),
(9, 'La vraie raison de la disparition des dinosaures : ____.'),
(10, 'Au mariage de mon cousin, tout le monde se souvient surtout de ____.'),
(11, 'Nouveau parfum de chips : ____.'),
(12, 'Ma mère m''a surpris avec ____.'),
(13, 'Le Wi-Fi de l''hôtel s''appelle « ____ ».'),
(14, 'Ce qui se cache vraiment au fond de mon frigo : ____.'),
(15, 'Pour mon anniversaire, je veux juste ____.'),
(16, 'Mon premier rencard s''est terminé à cause de ____.'),
(17, 'Le nouveau jeu télé du samedi soir : « Qui veut gagner ____ ? »'),
(18, 'Selon mon horoscope, cette semaine sera marquée par ____.'),
(19, 'La devise de notre famille : « ____ ».'),
(20, 'Ce que mon chat pense vraiment de moi : ____.'),
(21, 'Au Moyen Âge, on soignait tout avec ____.'),
(22, 'Mon voisin fait un bruit bizarre la nuit. Je pense que c''est ____.'),
(23, 'Le guide touristique déconseille formellement ____.'),
(24, 'Mon dernier achat en ligne à 3 h du matin : ____.'),
(25, 'Le thème de la soirée d''entreprise : ____.'),
(26, 'J''ai dû expliquer ____ à la douane.'),
(27, 'Ce qui a vraiment inspiré la Joconde : ____.'),
(28, 'Réunion parents-profs : « Votre enfant est obsédé par ____. »'),
(29, 'Il paraît que le bonheur, c''est ____.'),
(30, 'Le nouveau cours à la salle de sport : ____ pour débutants.'),
(31, 'Pourquoi j''ai été banni du camping ? ____.'),
(32, 'Le seul souvenir que je rapporte de vacances : ____.'),
(33, 'Nouvelle appli de rencontre, réservée aux fans de ____.'),
(34, 'Mon GPS m''a dit de tourner à droite, et je suis tombé sur ____.'),
(35, 'Le vrai contenu du coffre-fort de la Banque de France : ____.'),
(36, 'Ma résolution pour l''an prochain : moins de ____.'),
(37, 'Le dernier message de mon ex : « Rends-moi ____. »'),
(38, 'Aux Jeux olympiques de la flemme, la médaille d''or revient à ____.'),
(39, 'Mon talent caché : ____.'),
(40, 'Dans la lettre au père Noël de mon neveu : ____.'),
(41, 'Ce qu''on trouve toujours au fond d''un sac à main : ____.'),
(42, 'Nouvelle attraction au parc : le grand huit de ____.'),
(43, 'Sujet de philo : « Peut-on rire de ____ ? »'),
(44, 'J''ai raté mon permis à cause de ____.'),
(45, 'L''odeur étrange dans la voiture ? C''est ____.'),
(46, 'Cette année, le comité d''entreprise offre ____.'),
(47, 'La meilleure façon de rompre : ____.'),
(48, 'Mon coloc a laissé un mot : « Merci de ranger ____. »'),
(49, 'Le nouveau best-seller : « Réussir sa vie grâce à ____ ».'),
(50, 'Pendant le confinement, je me suis mis à ____.'),
(51, 'Les extraterrestres ne nous contactent pas à cause de ____.'),
(52, 'Le dessert du chef : une mousse de ____.'),
(53, 'À la fin du repas de famille, ça finit toujours par parler de ____.'),
(54, '____ : la nouvelle drogue des retraités.'),
(55, 'Ce que je murmure à mes plantes : ____.'),
(56, 'L''invention qui va tout changer : ____.'),
(57, 'Le vigile m''a arrêté à la sortie parce que j''avais ____.'),
(58, 'Ma photo de profil montre ____.'),
(59, 'Le prochain scandale à la mairie : ____.'),
(60, 'Mon plan retraite repose entièrement sur ____.'),
(61, 'Le pire truc à sortir pendant un enterrement : ____.'),
(62, '« Docteur, j''ai un problème avec ____. »'),
(63, 'Le nouveau goût de dentifrice : ____.'),
(64, 'Mon oncle raconte toujours la même histoire : celle de ____.'),
(65, '____ : c''est comme le vélo, ça ne s''oublie pas.'),
(66, 'J''ai dépensé tout mon héritage dans ____.'),
(67, 'Le sujet du bac cette année : ____.'),
(68, 'La météo annonce des averses de ____.'),
(69, 'Le plus gros mensonge de mon enfance : ____.'),
(70, 'À l''entretien d''embauche, j''ai parlé de ____. Grosse erreur.'),
(71, 'Ce qui rend une soirée pyjama inoubliable : ____.'),
(72, 'Le nom de mon futur groupe de rock : ____.'),
(73, 'Les voisins organisent une fête sur le thème : ____.'),
(74, 'La police a retrouvé ____ dans la boîte à gants.'),
(75, 'Pour séduire, rien ne vaut ____.'),
(76, 'Le sommelier recommande ____ avec le fromage.'),
(77, 'Mon rêve de cette nuit : ____ et moi sur une île déserte.'),
(78, 'Après trois verres, mon père ne parle plus que de ____.'),
(79, 'Le secret de la longévité des Français : ____.'),
(80, 'Le club de lecture de ma tante est en réalité un club de ____.'),
(81, 'La maîtresse a convoqué mes parents à cause de ____.'),
(82, 'Ce que je cherche en vain sur Internet : ____.'),
(83, 'En cas d''apocalypse, j''emporte ____.'),
(84, '____ : ça sent bon, mais c''est interdit.'),
(85, 'Le prochain film catastrophe : « L''attaque de ____ ».'),
(86, 'Mon dernier Uber s''est terminé avec ____.'),
(87, 'Ce que j''ai trouvé en rentrant de week-end : ____.'),
(88, 'Nouveau stage de développement personnel : « Libérez votre ____ intérieur ».'),
(89, 'Le cadeau le plus gênant de Noël : ____.'),
(90, 'Ce qui m''a valu un mois de privation de dessert : ____.'),
(93, 'Ce que je regrette le plus de ma soirée d''hier : ____.'),
(94, 'Mon mot de sécurité : « ____ ».'),
(95, 'Le secret d''une nuit réussie : ____.'),
(96, 'Ce que j''ai trouvé dans la table de nuit de mes parents : ____.'),
(97, 'Au lit, j''ai une seule exigence : ____.'),
(98, 'Mon ex m''a quitté à cause de ____.'),
(99, 'Le nouveau jouet pour adultes : ____.'),
(100, 'Ce que je fais quand mes colocs ne sont pas là : ____.'),
(101, 'Ma bio sur l''appli de rencontre : « Fan de ____. »'),
(102, 'Ce qui m''a valu une nuit au poste : ____.'),
(103, 'Mon premier baiser avait un goût de ____.'),
(104, 'Le thème de l''enterrement de vie de garçon : ____.'),
(105, 'Après la fête, on a retrouvé ____ dans la baignoire.'),
(106, 'Ce que je ne dirai jamais à mon médecin : ____.'),
(107, 'Ma technique de drague infaillible : ____.'),
(108, 'La honte du réveillon : ____.'),
(109, 'Ce que l''alcootest a vraiment détecté : ____.'),
(110, 'Le titre de ma sextape : « ____ ».'),
(111, 'Pour pimenter notre couple, on a essayé ____.'),
(112, 'Mon plus gros fantasme : ____.'),
(113, 'Ce qui s''est passé à Ibiza reste à Ibiza, sauf ____.'),
(114, 'Le message que je n''aurais jamais dû envoyer à mon patron : « ____ ».'),
(115, 'La vraie raison de mon arrêt maladie : ____.'),
(116, 'Dans l''historique de mon téléphone, on trouve surtout ____.'),
(117, 'Au spa, j''ai été viré pour ____.'),
(118, 'Le cadeau parfait pour une première nuit : ____.'),
(119, 'Le programme de l''enterrement de vie de jeune fille : ____.'),
(120, 'Ce que les voisins ont entendu cette nuit : ____.'),
(121, 'Le nouveau cocktail du bar : ____ on the beach.'),
(122, 'Le lendemain de soirée, je me suis réveillé avec ____.'),
(123, 'L''arbitre a sifflé penalty à cause de ____.'),
(124, 'Le nouveau chant des supporters : « ____ ! »'),
(125, 'La VAR a revu l''action et a découvert ____.'),
(126, 'Le coach a été viré pour ____.'),
(127, 'Au mercato, mon club a recruté ____.'),
(128, 'Pour motiver l''équipe à la mi-temps, le coach a sorti ____.'),
(129, 'Le vrai contenu de la gourde de l''entraîneur : ____.'),
(130, 'Carton rouge direct pour ____.'),
(131, 'Le nouveau sponsor sur le maillot : ____.'),
(132, 'Au foot à cinq du jeudi, on se dispute toujours pour ____.'),
(133, 'Le secret de ma célébration de but : ____.'),
(134, 'Pendant le match, un supporter a lancé ____ sur la pelouse.'),
(135, 'La tactique secrète du coach : ____.'),
(136, 'Dans le vestiaire, ça sent ____.'),
(137, 'Mon club de district a été racheté par ____.')
on conflict (id) do update set text=excluded.text, added_by=null, deleted_at=null;

select setval(pg_get_serial_sequence('public.questions','id'), (select max(id) from public.questions), true);
