-- SANITIZED SQUASHED BASELINE
--
-- The original production migration with this version predates repository
-- versioning. This file intentionally represents the current production schema
-- without secret app_settings values. Later historical versions are retained as
-- no-op markers so Supabase migration versions stay aligned with production.

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.questions (
  id integer generated by default as identity primary key,
  text text not null,
  created_at timestamptz not null default now(),
  added_by text,
  deleted_at timestamptz
);

create table if not exists public.answers (
  id integer generated by default as identity primary key,
  text text not null,
  created_at timestamptz not null default now(),
  added_by text,
  deleted_at timestamptz
);

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  status text not null default 'lobby' check (status in ('lobby','answering','judging','reveal','finished')),
  host_id uuid,
  reader_id uuid,
  question_id integer references public.questions(id),
  round integer not null default 0,
  winner_id uuid,
  winning_submission_id uuid,
  target_score integer not null default 5 check (target_score in (3,5,7,10)),
  hand_size integer not null default 7,
  used_questions integer[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  skips_used integer not null default 0,
  reward_used boolean not null default false,
  reward_kind text,
  reward_text text,
  created_by_hash text
);

create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  name text not null,
  token uuid not null default gen_random_uuid(),
  score integer not null default 0,
  seat integer not null,
  active boolean not null default true,
  last_seen timestamptz not null default now(),
  discard_round integer not null default 0,
  created_at timestamptz not null default now(),
  joined_by_hash text,
  unique(room_id, seat)
);

create table if not exists public.hands (
  player_id uuid not null references public.players(id) on delete cascade,
  answer_id integer not null references public.answers(id),
  room_id uuid not null references public.rooms(id) on delete cascade,
  primary key(player_id, answer_id)
);

create table if not exists public.used_answers (
  room_id uuid not null references public.rooms(id) on delete cascade,
  answer_id integer not null references public.answers(id),
  primary key(room_id, answer_id)
);

create table if not exists public.submissions (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  round integer not null,
  player_id uuid not null references public.players(id) on delete cascade,
  answer_id integer not null references public.answers(id),
  sort_key double precision not null default random(),
  unique(room_id, round, player_id)
);

create table if not exists public.app_settings (
  key text primary key,
  value text not null
);

create unique index if not exists questions_text_uniq on public.questions(lower(text));
create unique index if not exists answers_text_uniq on public.answers(lower(text));
create index if not exists rooms_question_idx on public.rooms(question_id);
create index if not exists players_room_idx on public.players(room_id);
create index if not exists hands_room_idx on public.hands(room_id);
create index if not exists hands_answer_idx on public.hands(answer_id);
create index if not exists used_answers_answer_idx on public.used_answers(answer_id);
create index if not exists submissions_player_idx on public.submissions(player_id);
create index if not exists submissions_answer_idx on public.submissions(answer_id);
create index if not exists rooms_created_by_hash_recent_idx on public.rooms(created_by_hash, created_at) where created_by_hash is not null;
create index if not exists players_joined_by_hash_recent_idx on public.players(joined_by_hash, created_at) where joined_by_hash is not null;

alter table public.questions enable row level security;
alter table public.answers enable row level security;
alter table public.rooms enable row level security;
alter table public.players enable row level security;
alter table public.hands enable row level security;
alter table public.used_answers enable row level security;
alter table public.submissions enable row level security;
alter table public.app_settings enable row level security;

revoke all on table public.questions, public.answers, public.rooms, public.players,
  public.hands, public.used_answers, public.submissions, public.app_settings
from anon, authenticated;

insert into public.app_settings(key, value)
values ('rate_pepper', gen_random_uuid()::text)
on conflict (key) do nothing;

create or replace function public._client_hash()
returns text
language plpgsql
stable
security definer
set search_path = ''
as $$
declare headers jsonb; ip text; pepper text;
begin
  begin
    headers := nullif(current_setting('request.headers', true), '')::jsonb;
  exception when others then headers := null;
  end;
  if headers is null then return null; end if;
  ip := nullif(btrim(split_part(coalesce(headers->>'x-forwarded-for', headers->>'cf-connecting-ip', ''), ',', 1)), '');
  if ip is null then return null; end if;
  select value into pepper from public.app_settings where key='rate_pepper';
  if pepper is null then return null; end if;
  return encode(extensions.digest(pepper || ':' || ip, 'sha256'), 'hex');
end
$$;

create or replace function public._is_admin(p_password text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare stored_hash text; ok boolean := false; cost integer := 0; client_hash text;
begin
  client_hash := coalesce(public._client_hash(), 'no-request-context');
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('bmp-admin:' || client_hash, 0));
  select value into stored_hash from public.app_settings where key='admin_hash' for update;
  if stored_hash is not null then ok := stored_hash = extensions.crypt(coalesce(p_password,''), stored_hash); end if;
  if not coalesce(ok,false) then perform pg_catalog.pg_sleep(1.5); return false; end if;
  begin cost := split_part(stored_hash,'$',3)::integer; exception when others then cost := 0; end;
  if cost < 10 then
    update public.app_settings set value=extensions.crypt(p_password, extensions.gen_salt('bf',10)) where key='admin_hash';
  end if;
  return true;
end
$$;

create or replace function public._clean_card(p_kind text, p_text text)
returns text
language plpgsql
immutable
set search_path = ''
as $$
declare t text; n int;
begin
  t := regexp_replace(trim(coalesce(p_text, '')), '\s+', ' ', 'g');
  if p_kind='q' then
    t := regexp_replace(t, '_{2,}', '____', 'g');
    if length(t)<5 then raise exception 'La question est trop courte.'; end if;
    if length(t)>150 then raise exception 'La question dépasse 150 caractères.'; end if;
    n := (length(t)-length(replace(t,'____','')))/4;
    if n=0 then raise exception 'Ajoute un trou « ____ » à l''endroit de la réponse.'; end if;
    if n>1 then raise exception 'Une question ne peut contenir qu''un seul trou.'; end if;
  else
    t := regexp_replace(t, '[.]+$', '');
    if length(t)<1 then raise exception 'La réponse est vide.'; end if;
    if length(t)>80 then raise exception 'La réponse dépasse 80 caractères.'; end if;
    if position('____' in t)>0 then raise exception 'Une réponse ne contient pas de trou.'; end if;
    t := upper(left(t,1)) || substr(t,2);
  end if;
  return t;
end
$$;

create or replace function public._check_card_rate()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select count(*) from public.questions where added_by is not null and created_at > now()-interval '10 minutes')
   + (select count(*) from public.answers where added_by is not null and created_at > now()-interval '10 minutes') >= 60 then
    raise exception 'Trop de cartes ajoutées d''un coup. Réessaie dans quelques minutes.';
  end if;
end
$$;

create or replace function public._new_code()
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare c text; chars text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
begin
  loop
    c := '';
    for i in 1..4 loop c := c || substr(chars, 1 + floor(random()*length(chars))::int, 1); end loop;
    exit when not exists(select 1 from public.rooms where code=c);
  end loop;
  return c;
end
$$;

create or replace function public._player(p_code text, p_token uuid)
returns public.players
language sql
stable
security definer
set search_path = ''
as $$
  select p.* from public.players p join public.rooms r on r.id=p.room_id
  where r.code=upper(trim(p_code)) and p.token=p_token and p.active
$$;

create or replace function public._next_reader(p_room uuid, p_after uuid)
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (select id from public.players where room_id=p_room and active
      and seat>coalesce((select seat from public.players where id=p_after),-1) order by seat limit 1),
    (select id from public.players where room_id=p_room and active order by seat limit 1))
$$;

create or replace function public._draw_question(p_room uuid)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare q int; used int[];
begin
  select used_questions into used from public.rooms where id=p_room;
  select id into q from public.questions where deleted_at is null and not(id=any(used)) order by random() limit 1;
  if q is null then
    used := '{}';
    select id into q from public.questions where deleted_at is null order by random() limit 1;
  end if;
  update public.rooms set used_questions=used||q where id=p_room;
  return q;
end
$$;

create or replace function public._deal(p_room uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare pl record; need int; hs int; avail int;
begin
  select hand_size into hs from public.rooms where id=p_room;
  for pl in select id from public.players where room_id=p_room and active order by seat loop
    select hs-count(*) into need from public.hands where player_id=pl.id;
    if need>0 then
      select count(*) into avail from public.answers a where a.deleted_at is null
        and not exists(select 1 from public.used_answers u where u.room_id=p_room and u.answer_id=a.id);
      if avail<need then
        delete from public.used_answers u where u.room_id=p_room
          and not exists(select 1 from public.hands h where h.room_id=p_room and h.answer_id=u.answer_id);
      end if;
      insert into public.hands(player_id,answer_id,room_id)
      select pl.id,a.id,p_room from public.answers a where a.deleted_at is null
        and not exists(select 1 from public.used_answers u where u.room_id=p_room and u.answer_id=a.id)
      order by random() limit need;
      insert into public.used_answers(room_id,answer_id)
      select p_room,h.answer_id from public.hands h where h.player_id=pl.id on conflict do nothing;
    end if;
  end loop;
end
$$;

create or replace function public._maybe_judge(p_room uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare r public.rooms;
begin
  select * into r from public.rooms where id=p_room;
  if r.status<>'answering' then return; end if;
  if not exists(
    select 1 from public.players p where p.room_id=p_room and p.active and p.id<>r.reader_id
      and not exists(select 1 from public.submissions s where s.room_id=p_room and s.round=r.round and s.player_id=p.id)
  ) and exists(select 1 from public.submissions s where s.room_id=p_room and s.round=r.round) then
    update public.rooms set status='judging',updated_at=now() where id=p_room;
  end if;
end
$$;

create or replace function public._start_round(p_room uuid, p_reader uuid, p_next_round integer)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare q int;
begin
  perform public._deal(p_room);
  q := public._draw_question(p_room);
  update public.rooms set status='answering',round=p_next_round,reader_id=p_reader,question_id=q,
    winner_id=null,winning_submission_id=null,skips_used=0,updated_at=now() where id=p_room;
end
$$;

create or replace function public._remove_player(p_player uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare pl public.players; r public.rooms; nr uuid;
begin
  select * into pl from public.players where id=p_player;
  if pl.id is null or not pl.active then return; end if;
  select * into r from public.rooms where id=pl.room_id for update;
  update public.players set active=false where id=p_player;
  delete from public.hands where player_id=p_player;
  if r.host_id=p_player then
    update public.rooms set host_id=(select id from public.players where room_id=r.id and active order by seat limit 1) where id=r.id;
  end if;
  if r.status in ('answering','judging','reveal') then
    if (select count(*) from public.players where room_id=r.id and active)<3 then
      if r.status<>'reveal' then
        insert into public.hands(player_id,answer_id,room_id)
        select s.player_id,s.answer_id,r.id from public.submissions s join public.players p on p.id=s.player_id and p.active
        where s.room_id=r.id and s.round=r.round on conflict do nothing;
        delete from public.submissions where room_id=r.id and round=r.round;
      end if;
      update public.rooms set status='lobby',updated_at=now() where id=r.id;
    elsif r.reader_id=p_player then
      nr := public._next_reader(r.id,p_player);
      if r.status<>'reveal' then
        insert into public.hands(player_id,answer_id,room_id)
        select s.player_id,s.answer_id,r.id from public.submissions s join public.players p on p.id=s.player_id and p.active
        where s.room_id=r.id and s.round=r.round on conflict do nothing;
        delete from public.submissions where room_id=r.id and round=r.round;
      end if;
      perform public._start_round(r.id,nr,r.round+1);
    elsif r.status in ('answering','judging') then
      delete from public.submissions where room_id=r.id and round=r.round and player_id=p_player;
      if r.status='judging' and not exists(select 1 from public.submissions where room_id=r.id and round=r.round) then
        update public.rooms set status='answering',updated_at=now() where id=r.id;
      elsif r.status='answering' then perform public._maybe_judge(r.id); end if;
    end if;
  end if;
  update public.rooms set updated_at=now() where id=r.id;
end
$$;

create or replace function public.add_question(p_text text, p_author text default null)
returns json
language plpgsql
security definer
set search_path = ''
as $$
declare t text; q public.questions;
begin
  t := public._clean_card('q',p_text);
  select * into q from public.questions where lower(text)=lower(t);
  if q.id is not null and q.deleted_at is null then raise exception 'Cette question existe déjà.'; end if;
  perform public._check_card_rate();
  if q.id is not null then update public.questions set deleted_at=null,text=t where id=q.id returning * into q;
  else insert into public.questions(text,added_by) values(t,coalesce(nullif(left(trim(p_author),20),''),'anonyme')) returning * into q; end if;
  return json_build_object('id',q.id,'text',q.text,'total',(select count(*) from public.questions where deleted_at is null));
end
$$;

create or replace function public.add_answer(p_text text, p_author text default null)
returns json
language plpgsql
security definer
set search_path = ''
as $$
declare t text; a public.answers;
begin
  t := public._clean_card('a',p_text);
  select * into a from public.answers where lower(text)=lower(t);
  if a.id is not null and a.deleted_at is null then raise exception 'Cette réponse existe déjà.'; end if;
  perform public._check_card_rate();
  if a.id is not null then update public.answers set deleted_at=null,text=t where id=a.id returning * into a;
  else insert into public.answers(text,added_by) values(t,coalesce(nullif(left(trim(p_author),20),''),'anonyme')) returning * into a; end if;
  return json_build_object('id',a.id,'text',a.text,'total',(select count(*) from public.answers where deleted_at is null));
end
$$;

create or replace function public.card_counts()
returns json
language sql
stable
security definer
set search_path = ''
as $$ select json_build_object('questions',(select count(*) from public.questions where deleted_at is null),'answers',(select count(*) from public.answers where deleted_at is null)) $$;

create or replace function public.create_room(p_name text, p_target integer default 5)
returns json
language plpgsql
security definer
set search_path = ''
as $$
declare r public.rooms; p public.players; n text:=left(trim(coalesce(p_name,'')),20); client_hash text; attempt integer;
begin
  if n='' then raise exception 'Choisis un pseudo.'; end if;
  if p_target is null or p_target not in(3,5,7,10) then raise exception 'Le score cible doit être 3, 5, 7 ou 10.'; end if;
  client_hash:=public._client_hash();
  if client_hash is not null then
    perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('bmp-create:'||client_hash,0));
    if (select count(*) from public.rooms where created_by_hash=client_hash and created_at>now()-interval '10 minutes')>=10 then
      raise exception 'Trop de parties créées récemment. Réessaie dans quelques minutes.';
    end if;
  end if;
  delete from public.rooms where updated_at<now()-interval '1 day';
  for attempt in 1..5 loop
    begin insert into public.rooms(code,target_score,created_by_hash) values(public._new_code(),p_target,client_hash) returning * into r; exit;
    exception when unique_violation then if attempt=5 then raise exception 'Impossible de générer un code de partie. Réessaie.'; end if; end;
  end loop;
  insert into public.players(room_id,name,seat,joined_by_hash) values(r.id,n,0,client_hash) returning * into p;
  update public.rooms set host_id=p.id where id=r.id;
  return json_build_object('code',r.code,'player_id',p.id,'token',p.token);
end
$$;

create or replace function public.join_room(p_code text, p_name text)
returns json
language plpgsql
security definer
set search_path = ''
as $$
declare r public.rooms; p public.players; n text:=left(trim(coalesce(p_name,'')),20); client_hash text;
begin
  if n='' then raise exception 'Choisis un pseudo.'; end if;
  client_hash:=public._client_hash();
  if client_hash is not null then
    perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('bmp-join:'||client_hash,0));
    if (select count(*) from public.players where joined_by_hash=client_hash and created_at>now()-interval '10 minutes')>=30 then
      raise exception 'Trop de tentatives de connexion récentes. Réessaie dans quelques minutes.';
    end if;
  end if;
  select * into r from public.rooms where code=upper(trim(p_code)) for update;
  if r.id is null then if client_hash is not null then perform pg_catalog.pg_sleep(0.15); end if; raise exception 'Aucune partie avec ce code.'; end if;
  if (select count(*) from public.players where room_id=r.id and active)>=12 then raise exception 'La partie est pleine (12 joueurs max).'; end if;
  if exists(select 1 from public.players where room_id=r.id and active and lower(name)=lower(n)) then raise exception 'Ce pseudo est déjà pris dans cette partie.'; end if;
  insert into public.players(room_id,name,seat,joined_by_hash)
  values(r.id,n,(select coalesce(max(seat),-1)+1 from public.players where room_id=r.id),client_hash) returning * into p;
  if r.status<>'lobby' then perform public._deal(r.id); end if;
  update public.rooms set updated_at=now() where id=r.id;
  return json_build_object('code',r.code,'player_id',p.id,'token',p.token);
end
$$;

create or replace function public.get_state(p_code text, p_token uuid)
returns json
language plpgsql
security definer
set search_path = ''
as $$
declare me public.players; r public.rooms;
begin
  me:=public._player(p_code,p_token); if me.id is null then raise exception 'Session expirée. Rejoins la partie à nouveau.'; end if;
  if me.last_seen<now()-interval '5 minutes' then update public.players set last_seen=now() where id=me.id; end if;
  select * into r from public.rooms where id=me.room_id;
  return json_build_object(
    'room',json_build_object('code',r.code,'status',r.status,'round',r.round,'target',r.target_score,'host_id',r.host_id,'reader_id',r.reader_id,'winner_id',r.winner_id,'winning_submission_id',r.winning_submission_id,'updated_at',r.updated_at,'skips_left',3-r.skips_used,'reward_used',r.reward_used,'reward_kind',r.reward_kind,'reward_text',r.reward_text,'submission_count',(select count(*) from public.submissions s where s.room_id=r.id and s.round=r.round)),
    'me',json_build_object('id',me.id,'name',me.name,'can_discard',r.status='answering' and r.reader_id<>me.id and me.discard_round<>r.round and not exists(select 1 from public.submissions s where s.room_id=r.id and s.round=r.round and s.player_id=me.id)),
    'question',(select text from public.questions where id=r.question_id),
    'players',(select coalesce(json_agg(json_build_object('id',p.id,'name',p.name,'score',p.score,'active',p.active,'submitted',exists(select 1 from public.submissions s where s.room_id=r.id and s.round=r.round and s.player_id=p.id)) order by p.seat),'[]'::json) from public.players p where p.room_id=r.id and (p.active or (r.status in('reveal','finished') and p.id=r.winner_id))),
    'hand',(select coalesce(json_agg(json_build_object('id',a.id,'text',a.text) order by a.text),'[]'::json) from public.hands h join public.answers a on a.id=h.answer_id where h.player_id=me.id),
    'my_submission',(select a.text from public.submissions s join public.answers a on a.id=s.answer_id where s.room_id=r.id and s.round=r.round and s.player_id=me.id),
    'submissions',case when r.status in('reveal','finished') or (r.status='judging' and r.reader_id=me.id) then
      (select coalesce(json_agg(json_build_object('id',s.id,'text',a.text,'author',case when r.status in('reveal','finished') then p.name end) order by s.sort_key),'[]'::json) from public.submissions s join public.answers a on a.id=s.answer_id join public.players p on p.id=s.player_id where s.room_id=r.id and s.round=r.round)
      else '[]'::json end);
end
$$;

create or replace function public.start_game(p_code text,p_token uuid)
returns void language plpgsql security definer set search_path='' as $$
declare me public.players; r public.rooms;
begin
  me:=public._player(p_code,p_token); if me.id is null then raise exception 'Session expirée. Rejoins la partie à nouveau.'; end if;
  select * into r from public.rooms where id=me.room_id for update;
  if r.host_id<>me.id then raise exception 'Seul l''hôte peut lancer la partie.'; end if;
  if r.status not in('lobby','finished') then raise exception 'La partie est déjà en cours.'; end if;
  if (select count(*) from public.players where room_id=r.id and active)<3 then raise exception 'Il faut au moins 3 joueurs.'; end if;
  if r.status='finished' then
    update public.players set score=0,discard_round=0 where room_id=r.id;
    delete from public.hands where room_id=r.id; delete from public.used_answers where room_id=r.id; delete from public.submissions where room_id=r.id;
    update public.rooms set used_questions='{}',round=0,reward_used=false,reward_kind=null,reward_text=null where id=r.id; r.round:=0;
  end if;
  perform public._start_round(r.id,public._next_reader(r.id,r.reader_id),r.round+1);
end $$;

create or replace function public.submit_answer(p_code text,p_token uuid,p_answer_id integer)
returns void language plpgsql security definer set search_path='' as $$
declare me public.players; r public.rooms;
begin
  me:=public._player(p_code,p_token); if me.id is null then raise exception 'Session expirée. Rejoins la partie à nouveau.'; end if;
  select * into r from public.rooms where id=me.room_id for update;
  if r.status<>'answering' then raise exception 'Les réponses sont fermées pour ce tour.'; end if;
  if r.reader_id=me.id then raise exception 'Tu lis la question ce tour-ci.'; end if;
  if exists(select 1 from public.submissions where room_id=r.id and round=r.round and player_id=me.id) then raise exception 'Tu as déjà joué une carte.'; end if;
  if not exists(select 1 from public.hands where player_id=me.id and answer_id=p_answer_id) then raise exception 'Cette carte n''est pas dans ta main.'; end if;
  insert into public.submissions(room_id,round,player_id,answer_id) values(r.id,r.round,me.id,p_answer_id);
  delete from public.hands where player_id=me.id and answer_id=p_answer_id;
  perform public._deal(r.id); perform public._maybe_judge(r.id); update public.rooms set updated_at=now() where id=r.id;
end $$;

create or replace function public.discard_card(p_code text,p_token uuid,p_answer_id integer)
returns void language plpgsql security definer set search_path='' as $$
declare me public.players; r public.rooms;
begin
  me:=public._player(p_code,p_token); if me.id is null then raise exception 'Session expirée. Rejoins la partie à nouveau.'; end if;
  select * into r from public.rooms where id=me.room_id for update;
  if r.status<>'answering' then raise exception 'Tu ne peux échanger une carte que pendant les réponses.'; end if;
  if r.reader_id=me.id then raise exception 'Tu lis la question ce tour-ci.'; end if;
  if exists(select 1 from public.submissions where room_id=r.id and round=r.round and player_id=me.id) then raise exception 'Tu as déjà joué une carte ce tour-ci.'; end if;
  if me.discard_round=r.round then raise exception 'Tu as déjà échangé une carte ce tour-ci.'; end if;
  if not exists(select 1 from public.hands where player_id=me.id and answer_id=p_answer_id) then raise exception 'Cette carte n''est pas dans ta main.'; end if;
  delete from public.hands where player_id=me.id and answer_id=p_answer_id;
  update public.players set discard_round=r.round where id=me.id; perform public._deal(r.id); update public.rooms set updated_at=now() where id=r.id;
end $$;

create or replace function public.force_judging(p_code text,p_token uuid)
returns void language plpgsql security definer set search_path='' as $$
declare me public.players; r public.rooms;
begin
  me:=public._player(p_code,p_token); if me.id is null then raise exception 'Session expirée. Rejoins la partie à nouveau.'; end if;
  select * into r from public.rooms where id=me.room_id for update;
  if me.id not in(r.reader_id,r.host_id) then raise exception 'Seul le lecteur ou l''hôte peut faire ça.'; end if;
  if r.status<>'answering' then raise exception 'Les réponses sont déjà fermées.'; end if;
  if not exists(select 1 from public.submissions where room_id=r.id and round=r.round) then raise exception 'Personne n''a encore répondu.'; end if;
  update public.rooms set status='judging',updated_at=now() where id=r.id;
end $$;

create or replace function public.pick_winner(p_code text,p_token uuid,p_submission_id uuid)
returns void language plpgsql security definer set search_path='' as $$
declare me public.players; r public.rooms; w uuid; sc integer;
begin
  me:=public._player(p_code,p_token); if me.id is null then raise exception 'Session expirée. Rejoins la partie à nouveau.'; end if;
  select * into r from public.rooms where id=me.room_id for update;
  if r.reader_id<>me.id then raise exception 'Seul le lecteur choisit la gagnante.'; end if;
  if r.status<>'judging' then raise exception 'Ce n''est pas le moment de voter.'; end if;
  select s.player_id into w from public.submissions s join public.players p on p.id=s.player_id and p.active where s.id=p_submission_id and s.room_id=r.id and s.round=r.round;
  if w is null then raise exception 'Réponse introuvable ou joueur parti.'; end if;
  update public.players set score=score+1 where id=w and active returning score into sc;
  if sc is null then raise exception 'Le joueur n''est plus actif.'; end if;
  update public.rooms set status=case when sc>=r.target_score then 'finished' else 'reveal' end,winner_id=w,winning_submission_id=p_submission_id,updated_at=now() where id=r.id;
end $$;

create or replace function public.next_round(p_code text,p_token uuid)
returns void language plpgsql security definer set search_path='' as $$
declare me public.players; r public.rooms;
begin
  me:=public._player(p_code,p_token); if me.id is null then raise exception 'Session expirée. Rejoins la partie à nouveau.'; end if;
  select * into r from public.rooms where id=me.room_id for update;
  if r.status<>'reveal' then raise exception 'Le tour n''est pas terminé.'; end if;
  if me.id<>r.reader_id and me.id<>r.host_id then raise exception 'Seul le lecteur ou l''hôte peut lancer le tour suivant.'; end if;
  perform public._start_round(r.id,public._next_reader(r.id,r.reader_id),r.round+1);
end $$;

create or replace function public.skip_question(p_code text,p_token uuid)
returns void language plpgsql security definer set search_path='' as $$
declare me public.players; r public.rooms; q int;
begin
  me:=public._player(p_code,p_token); if me.id is null then raise exception 'Session expirée. Rejoins la partie à nouveau.'; end if;
  select * into r from public.rooms where id=me.room_id for update;
  if r.reader_id<>me.id then raise exception 'Seul le lecteur peut changer la question.'; end if;
  if r.status<>'answering' then raise exception 'Trop tard pour changer la question.'; end if;
  if r.skips_used>=3 then raise exception 'Tu as déjà changé 3 fois de question.'; end if;
  if exists(select 1 from public.submissions where room_id=r.id and round=r.round) then raise exception 'Quelqu''un a déjà répondu à cette question.'; end if;
  q:=public._draw_question(r.id); update public.rooms set question_id=q,skips_used=skips_used+1,updated_at=now() where id=r.id;
end $$;

create or replace function public.kick_player(p_code text,p_token uuid,p_player_id uuid)
returns void language plpgsql security definer set search_path='' as $$
declare me public.players; r public.rooms;
begin
  me:=public._player(p_code,p_token); if me.id is null then raise exception 'Session expirée. Rejoins la partie à nouveau.'; end if;
  select * into r from public.rooms where id=me.room_id;
  if r.host_id<>me.id then raise exception 'Seul l''hôte peut retirer un joueur.'; end if;
  if p_player_id=me.id then raise exception 'Utilise « Quitter » pour partir.'; end if;
  if not exists(select 1 from public.players where id=p_player_id and room_id=r.id and active) then raise exception 'Joueur introuvable.'; end if;
  perform public._remove_player(p_player_id);
end $$;

create or replace function public.leave_room(p_code text,p_token uuid)
returns void language plpgsql security definer set search_path='' as $$
declare me public.players;
begin me:=public._player(p_code,p_token); if me.id is null then return; end if; perform public._remove_player(me.id); end $$;

create or replace function public.add_reward_card(p_code text,p_token uuid,p_kind text,p_text text)
returns json language plpgsql security definer set search_path='' as $$
declare me public.players; r public.rooms; res json;
begin
  me:=public._player(p_code,p_token); if me.id is null then raise exception 'Session expirée. Rejoins la partie à nouveau.'; end if;
  select * into r from public.rooms where id=me.room_id for update;
  if r.status<>'finished' or r.winner_id<>me.id then raise exception 'Seul le gagnant peut créer la carte bonus.'; end if;
  if r.reward_used then raise exception 'La carte bonus a déjà été créée.'; end if;
  if p_kind='q' then res:=public.add_question(p_text,me.name); elsif p_kind='a' then res:=public.add_answer(p_text,me.name); else raise exception 'Type de carte inconnu.'; end if;
  update public.rooms set reward_used=true,reward_kind=p_kind,reward_text=res->>'text',updated_at=now() where id=r.id;
  return res;
end $$;

create or replace function public.admin_check(p_password text)
returns boolean language sql security definer set search_path='' as $$ select public._is_admin(p_password) $$;

create or replace function public.admin_add_card(p_password text,p_kind text,p_text text)
returns json language plpgsql security definer set search_path='' as $$
begin
  if not public._is_admin(p_password) then raise exception 'Mot de passe incorrect.'; end if;
  if p_kind='q' then return public.add_question(p_text,'admin'); end if;
  if p_kind='a' then return public.add_answer(p_text,'admin'); end if;
  raise exception 'Type de carte inconnu.';
end $$;

create or replace function public.admin_delete_card(p_password text,p_kind text,p_id integer)
returns void language plpgsql security definer set search_path='' as $$
declare rm uuid;
begin
  if not public._is_admin(p_password) then raise exception 'Mot de passe incorrect.'; end if;
  if p_kind='q' then
    update public.questions set deleted_at=now() where id=p_id and deleted_at is null; if not found then raise exception 'Carte introuvable.'; end if;
  elsif p_kind='a' then
    update public.answers set deleted_at=now() where id=p_id and deleted_at is null; if not found then raise exception 'Carte introuvable.'; end if;
    for rm in select distinct room_id from public.hands where answer_id=p_id loop
      delete from public.hands where room_id=rm and answer_id=p_id; perform public._deal(rm); update public.rooms set updated_at=now() where id=rm;
    end loop;
  else raise exception 'Type de carte inconnu.'; end if;
end $$;

create or replace function public.admin_list_cards(p_password text,p_kind text,p_search text default '',p_offset integer default 0)
returns json language plpgsql security definer set search_path='' as $$
declare s text:='%'||lower(trim(coalesce(p_search,'')))||'%';
begin
  if not public._is_admin(p_password) then raise exception 'Mot de passe incorrect.'; end if;
  if p_kind='q' then
    return json_build_object('total',(select count(*) from public.questions q where q.deleted_at is null and lower(q.text) like s),'items',(select coalesce(json_agg(json_build_object('id',x.id,'text',x.text,'by',x.added_by) order by x.created_at desc,x.id desc),'[]'::json) from(select q.id,q.text,q.added_by,q.created_at from public.questions q where q.deleted_at is null and lower(q.text) like s order by q.created_at desc,q.id desc offset greatest(p_offset,0) limit 50)x));
  elsif p_kind='a' then
    return json_build_object('total',(select count(*) from public.answers a where a.deleted_at is null and lower(a.text) like s),'items',(select coalesce(json_agg(json_build_object('id',x.id,'text',x.text,'by',x.added_by) order by x.created_at desc,x.id desc),'[]'::json) from(select a.id,a.text,a.added_by,a.created_at from public.answers a where a.deleted_at is null and lower(a.text) like s order by a.created_at desc,a.id desc offset greatest(p_offset,0) limit 50)x));
  end if;
  raise exception 'Type de carte inconnu.';
end $$;

create or replace function public.admin_update_card(p_password text,p_kind text,p_id integer,p_text text)
returns json language plpgsql security definer set search_path='' as $$
declare t text;
begin
  if not public._is_admin(p_password) then raise exception 'Mot de passe incorrect.'; end if;
  t:=public._clean_card(p_kind,p_text);
  if p_kind='q' then
    if exists(select 1 from public.questions q where lower(q.text)=lower(t) and q.id<>p_id) then raise exception 'Une autre question a déjà ce texte.'; end if;
    update public.questions set text=t where id=p_id and deleted_at is null;
  elsif p_kind='a' then
    if exists(select 1 from public.answers a where lower(a.text)=lower(t) and a.id<>p_id) then raise exception 'Une autre réponse a déjà ce texte.'; end if;
    update public.answers set text=t where id=p_id and deleted_at is null;
  else raise exception 'Type de carte inconnu.'; end if;
  if not found then raise exception 'Carte introuvable.'; end if;
  return json_build_object('id',p_id,'text',t);
end $$;

-- Internal functions are never public API.
revoke all on function public._client_hash() from public,anon,authenticated;
revoke all on function public._is_admin(text) from public,anon,authenticated;
revoke all on function public._clean_card(text,text) from public,anon,authenticated;
revoke all on function public._check_card_rate() from public,anon,authenticated;
revoke all on function public._new_code() from public,anon,authenticated;
revoke all on function public._player(text,uuid) from public,anon,authenticated;
revoke all on function public._next_reader(uuid,uuid) from public,anon,authenticated;
revoke all on function public._draw_question(uuid) from public,anon,authenticated;
revoke all on function public._deal(uuid) from public,anon,authenticated;
revoke all on function public._maybe_judge(uuid) from public,anon,authenticated;
revoke all on function public._start_round(uuid,uuid,integer) from public,anon,authenticated;
revoke all on function public._remove_player(uuid) from public,anon,authenticated;
revoke all on function public.add_question(text,text) from public,anon,authenticated;
revoke all on function public.add_answer(text,text) from public,anon,authenticated;

-- Anonymous browser API. The app does not use Supabase Auth.
grant execute on function public.card_counts() to anon;
grant execute on function public.create_room(text,integer) to anon;
grant execute on function public.join_room(text,text) to anon;
grant execute on function public.get_state(text,uuid) to anon;
grant execute on function public.start_game(text,uuid) to anon;
grant execute on function public.submit_answer(text,uuid,integer) to anon;
grant execute on function public.discard_card(text,uuid,integer) to anon;
grant execute on function public.force_judging(text,uuid) to anon;
grant execute on function public.pick_winner(text,uuid,uuid) to anon;
grant execute on function public.next_round(text,uuid) to anon;
grant execute on function public.skip_question(text,uuid) to anon;
grant execute on function public.kick_player(text,uuid,uuid) to anon;
grant execute on function public.leave_room(text,uuid) to anon;
grant execute on function public.add_reward_card(text,uuid,text,text) to anon;
grant execute on function public.admin_check(text) to anon;
grant execute on function public.admin_add_card(text,text,text) to anon;
grant execute on function public.admin_delete_card(text,text,integer) to anon;
grant execute on function public.admin_list_cards(text,text,text,integer) to anon;
grant execute on function public.admin_update_card(text,text,integer,text) to anon;

revoke execute on function public.card_counts() from authenticated;
revoke execute on function public.create_room(text,integer) from authenticated;
revoke execute on function public.join_room(text,text) from authenticated;
revoke execute on function public.get_state(text,uuid) from authenticated;
revoke execute on function public.start_game(text,uuid) from authenticated;
revoke execute on function public.submit_answer(text,uuid,integer) from authenticated;
revoke execute on function public.discard_card(text,uuid,integer) from authenticated;
revoke execute on function public.force_judging(text,uuid) from authenticated;
revoke execute on function public.pick_winner(text,uuid,uuid) from authenticated;
revoke execute on function public.next_round(text,uuid) from authenticated;
revoke execute on function public.skip_question(text,uuid) from authenticated;
revoke execute on function public.kick_player(text,uuid,uuid) from authenticated;
revoke execute on function public.leave_room(text,uuid) from authenticated;
revoke execute on function public.add_reward_card(text,uuid,text,text) from authenticated;
revoke execute on function public.admin_check(text) from authenticated;
revoke execute on function public.admin_add_card(text,text,text) from authenticated;
revoke execute on function public.admin_delete_card(text,text,integer) from authenticated;
revoke execute on function public.admin_list_cards(text,text,text,integer) from authenticated;
revoke execute on function public.admin_update_card(text,text,integer,text) from authenticated;

alter default privileges in schema public revoke execute on functions from public,anon,authenticated;
alter default privileges in schema public revoke all on tables from anon,authenticated;
