-- Remplacement intégral du deck de questions par le deck fourni
-- (deck_phrases_a_trou.csv : 180 cartes DECK PREMIUM + 20 cartes RESERVE).
-- Les anciennes questions sont supprimées définitivement : les parties en cours
-- perdent la question tirée et repartent d'un historique vierge.
-- Les identifiants sont volontairement laissés à la séquence (et non forcés via
-- « overriding system value ») : la colonne est une identity dans le dépôt mais
-- un serial en production, seul ce formulaire fonctionne des deux côtés.

update public.rooms set question_id = null, used_questions = '{}';

delete from public.questions;

select setval(pg_get_serial_sequence('public.questions','id'), 1, false);

insert into public.questions(text) values
  ('____ a ruiné mon mariage.'),
  ('____ semble toujours être une bonne idée à trois heures du matin.'),
  ('Le véritable problème avec ____, c''est quand ça reste coincé.'),
  ('Selon mon médecin, ____ n''est pas censé être de cette couleur.'),
  ('En 2027, je voterai à coup sûr pour ____.'),
  ('Le tribunal a retenu ____ comme circonstance aggravante.'),
  ('Le magasin refuse les retours après utilisation de ____.'),
  ('Personne ne m''avait expliqué qu''il fallait retirer ____ avant utilisation.'),
  ('Le mariage proposait trois options : poisson, viande ou ____.'),
  ('____ paraît toujours plus gros quand on le voit en vrai.'),
  ('Le problème avec l''envie de ____, c''est qu''elle arrive rarement au bon moment.'),
  ('La minute de silence a été gâchée par ____.'),
  ('À partir de combien de ____ ça devient inquiétant ?'),
  ('Le don d''organes, c''est beau. Le don de ____, beaucoup moins.'),
  ('Le vendeur m''avait assuré que ____ était silencieux.'),
  ('____ n''est pas aussi propre que dans les films.'),
  ('Le notaire a refusé de lire à voix haute le passage concernant ____.'),
  ('Le formulaire ne prévoyait aucune case pour ____.'),
  ('Il faut vraiment être désespéré pour en arriver à ____.'),
  ('Ma mutuelle ne rembourse toujours pas ____.'),
  ('Ils ont installé des caméras à cause des gens qui venaient ____.'),
  ('La notice était pourtant claire : ne jamais approcher ____ d''une flamme.'),
  ('Mon assurance appelle ça « un sinistre ». Moi, j''appelle ça ____.'),
  ('Le contrôleur n''a rien voulu savoir pour ____.'),
  ('On m''a retiré mon permis à cause de ____.'),
  ('____ n''a jamais tué personne.'),
  ('Il reste encore un peu de ____ dans le congélateur.'),
  ('Sur le procès-verbal, l''agent a écrit : « présence anormale de ____ ».'),
  ('Mon oncle a une technique imparable pour ____.'),
  ('L''odeur est partie, mais pas le souvenir de ____.'),
  ('Dans ma famille, on ne parle jamais de ____.'),
  ('La douane a trouvé ____ dans ma valise, et ce n''était même pas à moi.'),
  ('Le curé a demandé si quelqu''un s''opposait à cette union. Mon frère a répondu ____.'),
  ('Il ne restait plus qu''une solution : ____.'),
  ('Le chirurgien a préféré ne pas expliquer d''où venait ____.'),
  ('Mon CV mentionne ____ dans la rubrique « centres d''intérêt ».'),
  ('Le pire, en colocation, c''est celui qui n''arrête pas de ____.'),
  ('Ils ont dû évacuer le musée à cause de ____.'),
  ('Rien de tel que ____ pour se réconcilier.'),
  ('Ma résolution du Nouvel An : arrêter de ____.'),
  ('Le test ADN a révélé ____.'),
  ('La réunion de copropriété a dégénéré à cause de ____.'),
  ('On devrait rendre ____ obligatoire dès 18 ans.'),
  ('Mon patron m''a surpris en train de ____.'),
  ('Il n''y a pas de honte à ____.'),
  ('Le juge a demandé pourquoi j''avais éprouvé le besoin de ____.'),
  ('Sur ma tombe, je veux qu''on grave ____.'),
  ('Dieu pardonne tout, sauf ____.'),
  ('J''ai appris à ____ avant d''apprendre à faire du vélo.'),
  ('L''avis une étoile disait simplement : « ____ ».'),
  ('Aux urgences, il vaut mieux ne pas mentionner ____.'),
  ('Le pharmacien a exigé une ordonnance pour ____.'),
  ('Sur la radio, on voyait clairement ____.'),
  ('L''infirmière m''a demandé si j''avais l''habitude de ____.'),
  ('J''ai été refusé au don du sang à cause de ____.'),
  ('Les effets secondaires : nausées, vertiges et ____.'),
  ('Depuis l''opération, je n''arrive plus à ____.'),
  ('Trois ans de thérapie pour comprendre que tout venait de ____.'),
  ('Il paraît que rêver de ____ est mauvais signe.'),
  ('L''entretien d''embauche se passait bien jusqu''à ____.'),
  ('La nouvelle charte interdit formellement de ____.'),
  ('Le séminaire de cohésion s''est terminé par ____.'),
  ('Mon arrêt maladie mentionnait ____.'),
  ('Le pot de départ a pris une tournure bizarre avec ____.'),
  ('Il y a désormais une formation obligatoire sur ____.'),
  ('Le programme du candidat tenait en trois mots : justice, transparence, ____.'),
  ('Une pétition circule contre ____.'),
  ('Le ministre a présenté ses excuses pour ____.'),
  ('Le débat a basculé quand il a été question de ____.'),
  ('Ils veulent mettre une taxe sur ____.'),
  ('La préfecture demande un justificatif de domicile et ____.'),
  ('Le référendum portait sur ____.'),
  ('En garde à vue, j''ai surtout regretté ____.'),
  ('Les gendarmes ont tout de suite remarqué ____.'),
  ('En prison, ça se monnaie très cher : ____.'),
  ('La caméra de surveillance a tout filmé, y compris ____.'),
  ('Il paraît qu''on peut aller en prison pour ____.'),
  ('À confesse, j''ai gardé pour moi l''épisode de ____.'),
  ('Le Vatican n''a toujours pas statué sur ____.'),
  ('Le carême, cette année, j''arrête de ____.'),
  ('Ils ont béni la maison, mais pas ____.'),
  ('Le témoin a commencé son discours par ____.'),
  ('Ma belle-mère m''a pardonné beaucoup de choses, mais jamais ____.'),
  ('Après quinze ans de mariage, on a arrêté de ____.'),
  ('La demande en mariage aurait été parfaite sans ____.'),
  ('Notre couple a survécu à ____.'),
  ('Le divorce a été prononcé aux torts exclusifs de ____.'),
  ('Dans mon testament, j''ai prévu une clause spéciale pour ____.'),
  ('Je veux que mon enterrement se termine par ____.'),
  ('La crémation a été retardée à cause de ____.'),
  ('L''héritage se résumait à une maison, deux dettes et ____.'),
  ('Chez mes parents, il y a une pièce fermée à clé à cause de ____.'),
  ('Le repas de Noël a tourné court à cause de ____.'),
  ('Ma tante poste des photos de ____ sur Facebook.'),
  ('Mon père m''a appris à ____.'),
  ('Le secret de famille, c''est ____.'),
  ('La garantie ne couvre pas ____.'),
  ('En rayon, c''était juste à côté de ____.'),
  ('Le livreur a laissé ____ devant la porte.'),
  ('Ils ont mis un antivol sur ____.'),
  ('Le mode d''emploi est en chinois, sauf le paragraphe sur ____.'),
  ('Le steward m''a demandé de ranger ____.'),
  ('Dans les toilettes d''un avion, on ne devrait pas pouvoir ____.'),
  ('Mon voisin de siège avait emporté ____.'),
  ('La voiture de location sentait ____.'),
  ('Six heures d''escale : largement le temps de ____.'),
  ('Le GPS n''avait pas prévu ____.'),
  ('La femme de ménage a trouvé ____ sous le lit.'),
  ('L''hôtel facture un supplément pour ____.'),
  ('Le club de vacances proposait une initiation à ____.'),
  ('Au camping, tout le monde t''entend ____.'),
  ('Le chef propose ce soir un risotto à ____.'),
  ('Il y avait ____ dans la soupe, et personne n''a rien dit.'),
  ('Le buffet à volonté a été supprimé à cause de ____.'),
  ('Il paraît qu''en Bretagne, c''est une tradition de ____.'),
  ('Après le troisième verre, ____ devient une évidence.'),
  ('Le lendemain, il restait des traces de ____ au plafond.'),
  ('La soirée a dégénéré quand on a décidé de ____.'),
  ('Le bal des pompiers : de la bière, des saucisses et ____.'),
  ('Personne ne se souvient de qui a proposé ____.'),
  ('Il faut environ trois semaines pour se remettre de ____.'),
  ('Ça ne se voit pas, mais ça s''entend : ____.'),
  ('La texture, c''est ce qui m''a le plus dérangé avec ____.'),
  ('On s''habitue à tout, même à ____.'),
  ('Le contrôle antidopage a révélé des traces de ____.'),
  ('L''échauffement consiste surtout à ____.'),
  ('L''arbitre a sorti un carton rouge pour ____.'),
  ('Le club cherche un sponsor depuis l''affaire ____.'),
  ('L''algorithme me recommande surtout ____.'),
  ('L''intelligence artificielle a refusé de ____.'),
  ('Le direct a été coupé à cause de ____.'),
  ('Mon historique de recherche, c''est 80 % de ____.'),
  ('C''est devenu viral pour de mauvaises raisons : ____.'),
  ('La télé-réalité de cette année : dix candidats, une villa et ____.'),
  ('Mon banquier a surligné la ligne concernant ____.'),
  ('J''ai déclaré ____ aux impôts, par honnêteté.'),
  ('Le prêt a été refusé à cause de ____.'),
  ('Je serais prêt à vendre un rein pour ____.'),
  ('La cagnotte en ligne était destinée à ____.'),
  ('Le sujet du bac de philo, cette année : « ____ ».'),
  ('En soirée étudiante, il y a toujours quelqu''un pour ____.'),
  ('Le vétérinaire a extrait ____ de l''estomac du chien.'),
  ('Le chat a ramené ____ dans le salon.'),
  ('Le zoo a fermé l''enclos après l''incident avec ____.'),
  ('L''agent immobilier a oublié de mentionner ____.'),
  ('Derrière le placo, on a trouvé ____.'),
  ('Le tuto ne précisait pas qu''il fallait ____.'),
  ('À l''armée, on m''a réformé pour ____.'),
  ('Le portique de sécurité a sonné à cause de ____.'),
  ('Le plan d''évacuation prévoit, en dernier recours, de ____.'),
  ('Alerte orange : la préfecture recommande d''éviter ____.'),
  ('Ça porte malheur de croiser ____ un vendredi 13.'),
  ('Mon horoscope annonce une semaine marquée par ____.'),
  ('L''œuvre s''intitule « ____ » et vaut trois millions.'),
  ('Le jury a été unanime : ____.'),
  ('En édition limitée, ____ coûte quatre fois plus cher.'),
  ('Au fond, la vie, c''est ____.'),
  ('____ ne résout rien, mais ça soulage.'),
  ('Il y a un âge pour ____, et je l''ai dépassé.'),
  ('____, c''est un art, pas une science.'),
  ('Le besoin de ____ devient inquiétant quand il faut commencer à le cacher.'),
  ('L''art de ____ se perd.'),
  ('Il faut une certaine confiance en soi pour ____.'),
  ('Ils ont dû afficher « Interdit de ____ ».'),
  ('On finit tous par ____.'),
  ('Je ne suis pas fier d''avoir dû ____.'),
  ('Pour de l''argent, je serais capable de ____.'),
  ('Il n''est jamais trop tard pour ____.'),
  ('À la retraite, j''aurai enfin le temps de ____.'),
  ('Ma plus grosse erreur a été de ____.'),
  ('Avant de juger, essayez au moins une fois de ____.'),
  ('Le stage d''intégration consistait à ____.'),
  ('La mairie a enfin pris position sur ____.'),
  ('Le conseil de discipline de la fac s''est réuni pour ____.'),
  ('Plus c''est interdit, meilleur c''est : ____.'),
  ('Ce goût bizarre, c''était ____.'),
  ('Quelqu''un doit bien se dévouer pour ____.'),
  ('C''est en tombant qu''on apprend à ____.'),
  ('Le secret d''un couple qui dure : ____ ensemble.'),
  ('On ne m''y reprendra plus à ____.'),
  ('Les voisins se sont plaints du bruit de ____.'),
  ('Mon frigo contient surtout ____.'),
  ('Il faut avoir confiance en quelqu''un pour ____ devant lui.'),
  ('Le week-end d''intégration incluait ____.'),
  ('Je ferais n''importe quoi pour ____.'),
  ('Dans la boîte à gants, il y avait ____.'),
  ('Le médecin m''a conseillé d''arrêter de ____.'),
  ('Le bruit venait du grenier. C''était ____.'),
  ('On ne devrait pas trouver ____ dans une salle d''attente.'),
  ('Ma playlist du dimanche matin, c''est ____.'),
  ('J''ai toujours rêvé de ____ sur un bateau.'),
  ('Il y a un tarif étudiant pour ____.'),
  ('Le SAV m''a répondu que ____ n''était pas un défaut.'),
  ('Mon voisin du dessus stocke ____ sur son balcon.'),
  ('C''est plus facile de demander pardon que d''obtenir la permission de ____.'),
  ('On a retrouvé ____ dans la machine à laver.'),
  ('À mon âge, ____ n''a plus le même goût.'),
  ('La recette de ma grand-mère contenait ____.'),
  ('Le plus dur, c''est de commencer à ____.'),
  ('L''ascenseur est resté bloqué avec ____ à l''intérieur.');

select setval(pg_get_serial_sequence('public.questions','id'), (select max(id) from public.questions), true);
