-- Troisième jeu : « Longueur d'onde ».
-- Un médium par manche, à tour de rôle (1, 2 ou 3 tours chacun, comme le juge
-- de Priorités). On tire une carte à deux extrêmes (« Bon » / « Mauvais ») et
-- une cible cachée sur le cadran, de 0 (gauche) à 100 (droite). Seul le médium
-- voit la cible ; il donne un indice. Chacun place ensuite son aiguille sur son
-- téléphone.
-- Points : 4 à 3 crans ou moins de la cible, 3 à 9 ou moins, 2 à 15 ou moins.
-- Le médium marque la moyenne (arrondie) des points des autres.

alter table public.rooms
  add column if not exists wave_card integer,
  add column if not exists wave_target integer,
  add column if not exists wave_clue text,
  add column if not exists used_waves integer[] not null default '{}';
alter table public.rooms drop constraint if exists rooms_mode_check;
alter table public.rooms add constraint rooms_mode_check check (mode in ('phrases', 'priorites', 'ondes'));
alter table public.rooms drop constraint if exists rooms_status_check;
alter table public.rooms add constraint rooms_status_check
  check (status in ('lobby', 'question_select', 'answering', 'judging', 'ranking', 'clue', 'guessing', 'reveal', 'finished'));

create table if not exists public.wave_cards (
  id integer generated by default as identity primary key,
  left_text text not null,
  right_text text not null,
  added_by text,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);
create unique index if not exists wave_cards_pair_uniq on public.wave_cards (lower(left_text), lower(right_text));
alter table public.wave_cards enable row level security;
revoke all on table public.wave_cards from public, anon, authenticated;

create table if not exists public.wave_guesses (
  room_id uuid not null references public.rooms(id) on delete cascade,
  round integer not null,
  player_id uuid not null references public.players(id) on delete cascade,
  value integer not null check (value between 0 and 100),
  points integer,
  primary key (room_id, round, player_id)
);
alter table public.wave_guesses enable row level security;
revoke all on table public.wave_guesses from public, anon, authenticated;

-- ---------- Nouvelle manche : médium suivant, carte et cible ----------
create or replace function public._begin_wave_round(p_room uuid, p_next_round integer)
 returns void language plpgsql security definer set search_path to '' as $function$
declare r public.rooms; j uuid; w uuid; c integer;
begin
  select * into r from public.rooms where id = p_room;
  select id into j from public.players
    where room_id = p_room and active and judge_count < r.judge_turns
    order by judge_count, seat limit 1;

  if j is null then
    select id into w from public.players where room_id = p_room and active order by score desc, seat limit 1;
    update public.rooms set status = 'finished', winner_id = w, winning_submission_id = null,
      phase_at = now(), updated_at = now() where id = p_room;
    return;
  end if;

  select id into c from public.wave_cards
    where deleted_at is null and not (id = any(r.used_waves)) order by random() limit 1;
  if c is null then
    update public.rooms set used_waves = '{}' where id = p_room;
    select id into c from public.wave_cards where deleted_at is null order by random() limit 1;
  end if;
  if c is null then raise exception 'Aucune carte Longueur d’onde disponible.'; end if;

  update public.players set judge_count = judge_count + 1 where id = j;
  update public.players set next_ack_round = 0 where room_id = p_room and active;
  delete from public.wave_guesses where room_id = p_room and round = p_next_round;
  update public.rooms set
    status = 'clue', round = p_next_round,
    previous_reader_id = reader_id, reader_id = j,
    wave_card = c, wave_target = 2 + floor(random() * 97)::integer, wave_clue = null,
    used_waves = (select used_waves from public.rooms where id = p_room) || c,
    question_id = null, question_choices = '{}',
    winner_id = null, winning_submission_id = null,
    phase_at = now(), updated_at = now()
  where id = p_room;
end $function$;

-- ---------- Décompte dès que tous les devineurs ont placé leur aiguille ----------
create or replace function public._maybe_wave_score(p_room uuid)
 returns void language plpgsql security definer set search_path to '' as $function$
declare r public.rooms;
begin
  select * into r from public.rooms where id = p_room;
  if r.status <> 'guessing' then return; end if;
  if exists (
    select 1 from public.players p
    where p.room_id = p_room and p.active and p.id <> r.reader_id
      and not exists (select 1 from public.wave_guesses g where g.room_id = p_room and g.round = r.round and g.player_id = p.id)
  ) then return; end if;

  update public.wave_guesses g set points =
      case when abs(g.value - r.wave_target) <= 3 then 4
           when abs(g.value - r.wave_target) <= 9 then 3
           when abs(g.value - r.wave_target) <= 15 then 2
           else 0 end
    where g.room_id = p_room and g.round = r.round;

  -- le médium n'a pas d'aiguille : sa ligne porte seulement ses points
  insert into public.wave_guesses(room_id, round, player_id, value, points)
  select p_room, r.round, r.reader_id, r.wave_target,
         coalesce((select round(avg(g.points))::integer from public.wave_guesses g
                   where g.room_id = p_room and g.round = r.round and g.player_id <> r.reader_id), 0)
  on conflict (room_id, round, player_id) do update set value = excluded.value, points = excluded.points;

  update public.players p set score = p.score + g.points
    from public.wave_guesses g
    where g.room_id = p_room and g.round = r.round and g.player_id = p.id and p.active;
  update public.rooms set status = 'reveal', phase_at = now(), updated_at = now() where id = p_room;
end $function$;

-- ---------- Le médium donne son indice ----------
create or replace function public.submit_clue(p_code text, p_token uuid, p_clue text)
 returns void language plpgsql security definer set search_path to '' as $function$
declare me public.players; r public.rooms; t text := regexp_replace(trim(coalesce(p_clue, '')), '\s+', ' ', 'g');
begin
  me := public._player(p_code, p_token);
  if me.id is null then raise exception 'Session expirée. Rejoins la partie à nouveau.'; end if;
  select * into r from public.rooms where id = me.room_id for update;
  if r.status <> 'clue' then raise exception 'Ce n’est pas le moment de donner l’indice.'; end if;
  if r.reader_id <> me.id then raise exception 'Seul le médium donne l’indice.'; end if;
  if t = '' then raise exception 'Écris un indice.'; end if;
  if char_length(t) > 60 then raise exception 'L’indice fait 60 caractères au maximum.'; end if;
  update public.rooms set wave_clue = t, status = 'guessing', phase_at = now(), updated_at = now() where id = r.id;
end $function$;

-- ---------- Un devineur place son aiguille (une seule fois) ----------
create or replace function public.submit_guess(p_code text, p_token uuid, p_value integer)
 returns void language plpgsql security definer set search_path to '' as $function$
declare me public.players; r public.rooms;
begin
  me := public._player(p_code, p_token);
  if me.id is null then raise exception 'Session expirée. Rejoins la partie à nouveau.'; end if;
  select * into r from public.rooms where id = me.room_id for update;
  if r.status <> 'guessing' then raise exception 'Ce n’est pas le moment de viser.'; end if;
  if r.reader_id = me.id then raise exception 'Le médium ne vise pas.'; end if;
  if p_value is null or p_value < 0 or p_value > 100 then raise exception 'Position invalide.'; end if;
  insert into public.wave_guesses(room_id, round, player_id, value)
  values (r.id, r.round, me.id, p_value) on conflict do nothing;
  if not found then raise exception 'Ta réponse est déjà envoyée.'; end if;
  perform public._maybe_wave_score(r.id);
  update public.rooms set updated_at = now() where id = r.id;
end $function$;

-- ---------- Aiguillage des manches ----------
create or replace function public._begin_round(p_room uuid, p_reader uuid, p_next_round integer)
 returns void language plpgsql security definer set search_path to '' as $function$
declare choices integer[]; m text;
begin
  select mode into m from public.rooms where id = p_room;
  if m = 'priorites' then
    perform public._begin_rank_round(p_room, p_next_round);
    return;
  end if;
  if m = 'ondes' then
    perform public._begin_wave_round(p_room, p_next_round);
    return;
  end if;
  perform public._deal(p_room);
  choices := public._question_choices(p_room);
  delete from public.submissions where room_id = p_room and round = p_next_round;
  update public.players set next_ack_round = 0 where room_id = p_room and active;
  update public.rooms set
    status = 'question_select', round = p_next_round,
    previous_reader_id = reader_id, reader_id = p_reader,
    question_id = null, question_choices = choices,
    winner_id = null, winning_submission_id = null,
    phase_at = now(), updated_at = now()
  where id = p_room;
end $function$;

-- ---------- Choix du jeu ----------
create or replace function public.create_room(p_name text, p_target integer default 5,
                                              p_mode text default 'phrases', p_turns integer default 2)
 returns json language plpgsql security definer set search_path to '' as $function$
declare
  r public.rooms;
  p public.players;
  n text := left(trim(coalesce(p_name, '')), 20);
  client_hash text;
  attempt integer;
begin
  if n = '' then
    raise exception 'Choisis un pseudo.';
  end if;
  if p_target is null or p_target not in (3, 5, 7, 10) then
    raise exception 'Le score cible doit être 3, 5, 7 ou 10.';
  end if;
  if p_mode is null or p_mode not in ('phrases', 'priorites', 'ondes') then
    raise exception 'Jeu inconnu.';
  end if;
  if p_turns is null or p_turns not in (1, 2, 3) then
    raise exception 'Le nombre de tours doit être 1, 2 ou 3.';
  end if;

  client_hash := public._client_hash();

  if client_hash is not null then
    perform pg_catalog.pg_advisory_xact_lock(
      pg_catalog.hashtextextended('bmp-create:' || client_hash, 0)
    );
    if (
      select count(*)
      from public.rooms x
      where x.created_by_hash = client_hash
        and x.created_at > now() - interval '10 minutes'
    ) >= 10 then
      raise exception 'Trop de parties créées récemment. Réessaie dans quelques minutes.';
    end if;
  end if;

  delete from public.rooms
  where updated_at < now() - interval '1 day';

  for attempt in 1..5 loop
    begin
      insert into public.rooms(code, target_score, mode, judge_turns, created_by_hash)
      values (public._new_code(), p_target, p_mode, p_turns, client_hash)
      returning * into r;
      exit;
    exception when unique_violation then
      if attempt = 5 then
        raise exception 'Impossible de générer un code de partie. Réessaie.';
      end if;
    end;
  end loop;

  insert into public.players(room_id, name, seat, joined_by_hash)
  values (r.id, n, 0, client_hash)
  returning * into p;

  update public.rooms
  set host_id = p.id
  where id = r.id;

  return json_build_object('code', r.code, 'player_id', p.id, 'token', p.token);
end
$function$;

create or replace function public.set_room_options(p_code text, p_token uuid, p_mode text, p_target integer, p_turns integer)
 returns void language plpgsql security definer set search_path to '' as $function$
declare me public.players; r public.rooms;
begin
  me := public._player(p_code, p_token);
  if me.id is null then raise exception 'Session expirée. Rejoins la partie à nouveau.'; end if;
  select * into r from public.rooms where id = me.room_id for update;
  if r.host_id <> me.id then raise exception 'Seul l’hôte choisit le jeu.'; end if;
  if r.status <> 'lobby' then raise exception 'Le jeu se choisit depuis le salon.'; end if;
  if p_mode is null or p_mode not in ('phrases', 'priorites', 'ondes') then raise exception 'Jeu inconnu.'; end if;
  if p_target is null or p_target not in (3, 5, 7, 10) then raise exception 'Le score cible doit être 3, 5, 7 ou 10.'; end if;
  if p_turns is null or p_turns not in (1, 2, 3) then raise exception 'Le nombre de tours doit être 1, 2 ou 3.'; end if;
  update public.rooms set mode = p_mode, target_score = p_target, judge_turns = p_turns, updated_at = now()
    where id = r.id;
end $function$;

create or replace function public.start_game(p_code text, p_token uuid)
 returns void language plpgsql security definer set search_path to '' as $function$
declare me public.players; r public.rooms; rd uuid;
begin
 me:=public._player(p_code,p_token); if me.id is null then raise exception 'Session expirée. Rejoins la partie à nouveau.'; end if;
 select * into r from public.rooms where id=me.room_id for update;
 if r.host_id<>me.id then raise exception 'Seul l’hôte peut lancer la partie.'; end if;
 if r.status<>'lobby' then raise exception 'La partie est déjà en cours.'; end if;
 if (select count(*) from public.players where room_id=r.id and active)<3 then raise exception 'Il faut au moins 3 joueurs.'; end if;
 if exists(select 1 from public.players where room_id=r.id and active and not ready) then raise exception 'Tous les joueurs doivent être prêts.'; end if;
 update public.players set score=0,discard_round=0,next_ack_round=0,continue_requested=false,judge_count=0 where room_id=r.id and active;
 delete from public.hands where room_id=r.id; delete from public.used_answers where room_id=r.id; delete from public.submissions where room_id=r.id;
 delete from public.rankings where room_id=r.id;
 delete from public.wave_guesses where room_id=r.id;
 update public.rooms set used_questions='{}',round=0,previous_reader_id=null,reader_id=null,rank_cards='{}',
   wave_card=null,wave_target=null,wave_clue=null where id=r.id;
 rd:=public._random_reader(r.id,null);
 perform public._begin_round(r.id,rd,1);
end $function$;

-- ---------- Départs : le médium qui part relance la manche ----------
create or replace function public._remove_player(p_player uuid)
 returns void language plpgsql security definer set search_path to '' as $function$
declare pl public.players; r public.rooms; nr uuid;
begin
  select * into pl from public.players where id = p_player;
  if pl.id is null or not pl.active then return; end if;

  select * into r from public.rooms where id = pl.room_id for update;

  update public.players set active = false where id = p_player;
  delete from public.hands where player_id = p_player;

  if r.host_id = p_player then
    update public.rooms
    set host_id = (select id from public.players where room_id = r.id and active order by seat limit 1)
    where id = r.id;
  end if;

  if r.status in ('question_select', 'answering', 'judging', 'ranking', 'clue', 'guessing', 'reveal') then
    if (select count(*) from public.players where room_id = r.id and active) < 3 then
      if r.status in ('answering', 'judging') then
        perform public._return_submissions(r.id, r.round);
      end if;
      update public.rooms set status = 'lobby', phase_at = now(), updated_at = now() where id = r.id;

    elsif r.reader_id = p_player then
      nr := public._random_reader(r.id, p_player);
      if r.status in ('answering', 'judging') then
        perform public._return_submissions(r.id, r.round);
      end if;
      perform public._begin_round(r.id, nr, case when r.status = 'question_select' then r.round else r.round + 1 end);

    elsif r.status = 'ranking' then
      delete from public.rankings where room_id = r.id and round = r.round and player_id = p_player;
      perform public._maybe_score(r.id);

    elsif r.status = 'guessing' then
      delete from public.wave_guesses where room_id = r.id and round = r.round and player_id = p_player;
      perform public._maybe_wave_score(r.id);

    elsif r.status in ('answering', 'judging') then
      delete from public.submissions where room_id = r.id and round = r.round and player_id = p_player;
      if r.status = 'judging'
         and not exists (select 1 from public.submissions where room_id = r.id and round = r.round) then
        update public.rooms set status = 'answering', phase_at = now(), updated_at = now() where id = r.id;
      elsif r.status = 'answering' then
        perform public._maybe_judge(r.id);
      end if;
    end if;
  end if;

  update public.rooms set updated_at = now() where id = r.id;
end $function$;

create or replace function public.reap_idle(p_code text, p_token uuid)
 returns void language plpgsql security definer set search_path to '' as $function$
declare me public.players; r public.rooms; pl record; rd uuid;
begin
  me := public._player(p_code, p_token);
  if me.id is null then return; end if;
  select * into r from public.rooms where id = me.room_id for update;
  if r.id is null then return; end if;
  if now() - r.phase_at < interval '120 seconds' then return; end if;

  if r.status in ('question_select', 'clue') then
    perform public._remove_player(r.reader_id);

  elsif r.status = 'answering' then
    for pl in
      select p.id from public.players p
      where p.room_id = r.id and p.active and p.id <> r.reader_id
        and not exists (
          select 1 from public.submissions s
          where s.room_id = r.id and s.round = r.round and s.player_id = p.id
        )
    loop
      perform public._remove_player(pl.id);
    end loop;
    perform public._maybe_judge(r.id);

  elsif r.status = 'ranking' then
    -- les devineurs d'abord : retirer le juge relance aussitôt une autre manche
    for pl in
      select p.id from public.players p
      where p.room_id = r.id and p.active
        and not exists (
          select 1 from public.rankings k
          where k.room_id = r.id and k.round = r.round and k.player_id = p.id
        )
      order by (p.id = r.reader_id)
    loop
      perform public._remove_player(pl.id);
    end loop;
    perform public._maybe_score(r.id);

  elsif r.status = 'guessing' then
    for pl in
      select p.id from public.players p
      where p.room_id = r.id and p.active and p.id <> r.reader_id
        and not exists (
          select 1 from public.wave_guesses g
          where g.room_id = r.id and g.round = r.round and g.player_id = p.id
        )
    loop
      perform public._remove_player(pl.id);
    end loop;
    perform public._maybe_wave_score(r.id);

  elsif r.status = 'judging' then
    perform public._remove_player(r.reader_id);

  elsif r.status = 'reveal' then
    rd := public._random_reader(r.id, r.reader_id);
    perform public._begin_round(r.id, rd, r.round + 1);
  end if;
end $function$;

-- ---------- Bots : indice bidon, aiguille près de la cible ----------
create or replace function public.bot_step(p_code text, p_token uuid)
 returns void language plpgsql security definer set search_path to '' as $function$
declare me public.players; r public.rooms; b public.players; aid integer; aid2 integer; sid uuid; qid integer; n int; sc int; rd uuid;
begin
  me := public._player(p_code, p_token);
  if me.id is null then raise exception 'Session expirée. Rejoins la partie à nouveau.'; end if;
  select * into r from public.rooms where id = me.room_id for update;

  if r.status = 'question_select' then
    select * into b from public.players where id = r.reader_id and active and is_bot;
    if b.id is not null then
      select x into qid from unnest(r.question_choices) x order by random() limit 1;
      update public.rooms set question_id = qid, used_questions = used_questions || qid,
        question_choices = '{}', status = 'answering', phase_at = now(), updated_at = now() where id = r.id;
    end if;

  elsif r.status = 'answering' then
    select blanks into n from public.questions where id = r.question_id;
    n := coalesce(n, 1);
    for b in select * from public.players p where p.room_id = r.id and p.active and p.is_bot and p.id <> r.reader_id
             and not exists(select 1 from public.submissions s where s.room_id = r.id and s.round = r.round and s.player_id = p.id) loop
      aid := null; aid2 := null;
      select h.answer_id into aid from public.hands h where h.player_id = b.id order by random() limit 1;
      if n = 2 then
        select h.answer_id into aid2 from public.hands h where h.player_id = b.id and h.answer_id <> aid order by random() limit 1;
      end if;
      if aid is not null and (n = 1 or aid2 is not null) then
        insert into public.submissions(room_id, round, player_id, answer_id, answer_id2)
        values (r.id, r.round, b.id, aid, aid2) on conflict do nothing;
        delete from public.hands where player_id = b.id and answer_id in (aid, aid2);
      end if;
    end loop;
    perform public._deal(r.id);
    perform public._maybe_judge(r.id);
    update public.rooms set updated_at = now() where id = r.id;

  elsif r.status = 'ranking' then
    for b in select * from public.players p where p.room_id = r.id and p.active and p.is_bot
             and not exists(select 1 from public.rankings k where k.room_id = r.id and k.round = r.round and k.player_id = p.id) loop
      insert into public.rankings(room_id, round, player_id, cards)
      values (r.id, r.round, b.id, (select array_agg(x order by random()) from unnest(r.rank_cards) x))
      on conflict do nothing;
    end loop;
    perform public._maybe_score(r.id);
    update public.rooms set updated_at = now() where id = r.id;

  elsif r.status = 'clue' then
    if exists(select 1 from public.players where id = r.reader_id and active and is_bot) then
      update public.rooms set wave_clue = 'Indice de bot (vers ' || r.wave_target || ')',
        status = 'guessing', phase_at = now(), updated_at = now() where id = r.id;
    end if;

  elsif r.status = 'guessing' then
    for b in select * from public.players p where p.room_id = r.id and p.active and p.is_bot and p.id <> r.reader_id
             and not exists(select 1 from public.wave_guesses g where g.room_id = r.id and g.round = r.round and g.player_id = p.id) loop
      insert into public.wave_guesses(room_id, round, player_id, value)
      values (r.id, r.round, b.id, greatest(0, least(100, r.wave_target - 20 + floor(random() * 41)::integer)))
      on conflict do nothing;
    end loop;
    perform public._maybe_wave_score(r.id);
    update public.rooms set updated_at = now() where id = r.id;

  elsif r.status = 'judging' and exists(select 1 from public.players where id = r.reader_id and active and is_bot) then
    select s.id, s.player_id into sid, b.id from public.submissions s
      join public.players p on p.id = s.player_id and p.active
      where s.room_id = r.id and s.round = r.round order by random() limit 1;
    if sid is not null then
      update public.players set score = score + 1 where id = b.id returning score into sc;
      update public.rooms set status = case when sc >= r.target_score then 'finished' else 'reveal' end,
        winner_id = b.id, winning_submission_id = sid, phase_at = now(), updated_at = now() where id = r.id;
    end if;

  elsif r.status = 'reveal' then
    update public.players set next_ack_round = r.round
      where room_id = r.id and active and is_bot and next_ack_round <> r.round;
    if not exists(select 1 from public.players where room_id = r.id and active and next_ack_round <> r.round) then
      rd := public._random_reader(r.id, r.reader_id);
      perform public._begin_round(r.id, rd, r.round + 1);
    else
      update public.rooms set updated_at = now() where id = r.id;
    end if;

  elsif r.status = 'finished' then
    update public.players set continue_requested = true
      where room_id = r.id and active and is_bot and not continue_requested;
    if not exists(select 1 from public.players where room_id = r.id and active and not continue_requested) then
      update public.players set ready = false, score = 0, discard_round = 0, next_ack_round = 0, continue_requested = false
        where room_id = r.id and active;
      delete from public.hands where room_id = r.id;
      delete from public.used_answers where room_id = r.id;
      delete from public.submissions where room_id = r.id;
      update public.rooms set status = 'lobby', round = 0, reader_id = null, previous_reader_id = null,
        question_id = null, question_choices = '{}', winner_id = null, winning_submission_id = null,
        used_questions = '{}', phase_at = now(), updated_at = now() where id = r.id;
    else
      update public.rooms set updated_at = now() where id = r.id;
    end if;
  end if;
end $function$;

-- ---------- État : carte, indice, cible (au médium seul avant la révélation), aiguilles ----------
create or replace function public.get_state(p_code text, p_token uuid)
 returns json language plpgsql security definer set search_path to '' as $function$
declare me public.players; r public.rooms;
begin
 me:=public._player(p_code,p_token); if me.id is null then raise exception 'Session expirée. Rejoins la partie à nouveau.'; end if;
 if me.last_seen<now()-interval '5 minutes' then update public.players set last_seen=now() where id=me.id; end if;
 select * into r from public.rooms where id=me.room_id;
 return json_build_object(
 'room',json_build_object('code',r.code,'status',r.status,'round',r.round,'target',r.target_score,'mode',r.mode,'turns',r.judge_turns,'host_id',r.host_id,'reader_id',r.reader_id,'winner_id',r.winner_id,'winning_submission_id',r.winning_submission_id,'updated_at',r.updated_at,'phase_at',r.phase_at,'submission_count',(select count(*) from public.submissions s where s.room_id=r.id and s.round=r.round)),
 'me',json_build_object('id',me.id,'name',me.name,'ready',me.ready,'next_ack',me.next_ack_round,'continue_requested',me.continue_requested,'can_discard',r.status='answering' and r.reader_id<>me.id and me.discard_round<>r.round and not exists(select 1 from public.submissions s where s.room_id=r.id and s.round=r.round and s.player_id=me.id)),
 'question',(select q.text from public.questions q where q.id=r.question_id),
 'blanks',coalesce((select q.blanks from public.questions q where q.id=r.question_id),1),
 'question_choices',case when r.status='question_select' and r.reader_id=me.id then (select coalesce(json_agg(json_build_object('id',q.id,'text',q.text)),'[]'::json) from public.questions q where q.id=any(r.question_choices)) else '[]'::json end,
 'players',(select coalesce(json_agg(json_build_object('id',p.id,'name',p.name,'score',p.score,'active',p.active,'ready',p.ready,'is_bot',p.is_bot,'next_ack',p.next_ack_round,'continue_requested',p.continue_requested,'judge_count',p.judge_count,
    'submitted',exists(select 1 from public.submissions s where s.room_id=r.id and s.round=r.round and s.player_id=p.id),
    'ranked',exists(select 1 from public.rankings k where k.room_id=r.id and k.round=r.round and k.player_id=p.id),
    'guessed',exists(select 1 from public.wave_guesses g where g.room_id=r.id and g.round=r.round and g.player_id=p.id)) order by p.seat),'[]'::json)
   from public.players p where p.room_id=r.id and (p.active or (r.status in('reveal','finished') and p.id=r.winner_id))),
 'hand',(select coalesce(json_agg(json_build_object('id',a.id,'text',a.text,'form',a.form) order by a.text),'[]'::json) from public.hands h join public.answers a on a.id=h.answer_id where h.player_id=me.id),
 'my_cards',(select coalesce(json_agg(json_build_object('text',a.text,'form',a.form) order by x.rang),'[]'::json)
             from public.submissions s
             cross join lateral unnest(array_remove(array[s.answer_id,s.answer_id2],null)) with ordinality as x(aid,rang)
             join public.answers a on a.id=x.aid
             where s.room_id=r.id and s.round=r.round and s.player_id=me.id),
 'submissions',case when r.status in('reveal','finished') or (r.status='judging' and r.reader_id=me.id) then
   (select coalesce(json_agg(json_build_object('id',s.id,'author',case when r.status in('reveal','finished') then p.name end,
      'cards',(select coalesce(json_agg(json_build_object('text',a.text,'form',a.form) order by x.rang),'[]'::json)
               from unnest(array_remove(array[s.answer_id,s.answer_id2],null)) with ordinality as x(aid,rang)
               join public.answers a on a.id=x.aid)) order by s.sort_key),'[]'::json)
    from public.submissions s join public.players p on p.id=s.player_id
    where s.room_id=r.id and s.round=r.round) else '[]'::json end,
 'rank_cards',case when r.mode='priorites' and r.status in('ranking','reveal','finished') then
   (select coalesce(json_agg(json_build_object('id',a.id,'text',a.text,'kind',a.kind) order by x.i),'[]'::json)
    from unnest(r.rank_cards) with ordinality as x(aid,i) join public._rank_pool(true) a on a.id=x.aid) else '[]'::json end,
 'my_ranking',(select k.cards from public.rankings k where k.room_id=r.id and k.round=r.round and k.player_id=me.id),
 'rankings',case when r.mode='priorites' and r.status in('reveal','finished') then
   (select coalesce(json_agg(json_build_object('player_id',k.player_id,'cards',k.cards,'points',k.points)),'[]'::json)
    from public.rankings k where k.room_id=r.id and k.round=r.round) else '[]'::json end,
 'wave',case when r.mode='ondes' and r.status in('clue','guessing','reveal','finished') and r.wave_card is not null then
   json_build_object(
     'left',(select c.left_text from public.wave_cards c where c.id=r.wave_card),
     'right',(select c.right_text from public.wave_cards c where c.id=r.wave_card),
     'clue',r.wave_clue,
     'target',case when r.reader_id=me.id or r.status in('reveal','finished') then r.wave_target end,
     'my_guess',(select g.value from public.wave_guesses g where g.room_id=r.id and g.round=r.round and g.player_id=me.id and g.player_id<>r.reader_id),
     'guesses',case when r.status in('reveal','finished') then
       (select coalesce(json_agg(json_build_object('player_id',g.player_id,'value',g.value,'points',g.points)),'[]'::json)
        from public.wave_guesses g where g.room_id=r.id and g.round=r.round) else '[]'::json end)
   end);
end $function$;

revoke all on function public._begin_wave_round(uuid, integer) from public, anon, authenticated;
revoke all on function public._maybe_wave_score(uuid) from public, anon, authenticated;
revoke all on function public._begin_round(uuid, uuid, integer) from public, anon, authenticated;
revoke all on function public._remove_player(uuid) from public, anon, authenticated;
revoke all on function public.submit_clue(text, uuid, text) from public, anon, authenticated;
grant execute on function public.submit_clue(text, uuid, text) to anon;
revoke all on function public.submit_guess(text, uuid, integer) from public, anon, authenticated;
grant execute on function public.submit_guess(text, uuid, integer) to anon;
revoke all on function public.create_room(text, integer, text, integer) from public, anon, authenticated;
grant execute on function public.create_room(text, integer, text, integer) to anon;
revoke all on function public.set_room_options(text, uuid, text, integer, integer) from public, anon, authenticated;
grant execute on function public.set_room_options(text, uuid, text, integer, integer) to anon;
revoke all on function public.start_game(text, uuid) from public, anon, authenticated;
grant execute on function public.start_game(text, uuid) to anon;
revoke all on function public.reap_idle(text, uuid) from public, anon, authenticated;
grant execute on function public.reap_idle(text, uuid) to anon;
revoke all on function public.bot_step(text, uuid) from public, anon, authenticated;
grant execute on function public.bot_step(text, uuid) to anon;
revoke all on function public.get_state(text, uuid) from public, anon, authenticated;
grant execute on function public.get_state(text, uuid) to anon;

-- ---------- Premier paquet : deux extrêmes par carte ----------
insert into public.wave_cards(left_text, right_text) values
('Bon','Mauvais'),('Problématique','Exemplaire'),('Passionnant','Ennuyeux'),
('Ville où on adorerait habiter','Ville où on détesterait habiter'),('Héros charismatique','Héros éclaté'),
('Chaud','Froid'),('Sous-coté','Surcoté'),('Facile à dire','Difficile à dire'),('Inutile','Indispensable'),
('Romantique','Pas romantique du tout'),('Sain','Malsain'),('Ringard','Stylé'),('Doux','Rugueux'),
('Pour les enfants','Pour les adultes'),('Bon film','Mauvais film'),('Bonne série','Mauvaise série'),
('Bonne chanson','Mauvaise chanson'),('Ça sent bon','Ça sent mauvais'),('Calme','Bruyant'),
('Rare','Courant'),('Talent inné','Talent qui se travaille'),('Pas cher','Hors de prix'),
('Léger','Lourd'),('Vieux jeu','Moderne'),('Effrayant','Rassurant'),('Mignon','Moche'),
('Sport facile','Sport difficile'),('Petit plaisir','Gros plaisir'),('Gentil','Méchant'),
('Classe','Vulgaire'),('Rapide','Lent'),('Dangereux','Sans danger'),('Bonne idée','Mauvaise idée'),
('Fait pour l’été','Fait pour l’hiver'),('Ennuyeux à faire','Amusant à faire'),('Célèbre','Inconnu'),
('Mauvais cadeau','Bon cadeau'),('Bon prénom','Mauvais prénom'),('Bon métier','Mauvais métier'),
('Plat raffiné','Plat de cantine'),('Bon dessert','Mauvais dessert'),('Bonne excuse','Mauvaise excuse'),
('Péché mignon','Péché impardonnable'),('Tout le monde aime','Tout le monde déteste'),
('Bon conseil','Mauvais conseil'),('Mauvais superpouvoir','Bon superpouvoir'),('Sérieux','Ridicule'),
('Utile en soirée','Inutile en soirée'),('Normal','Bizarre'),('Fragile','Solide'),
('Bon premier rendez-vous','Mauvais premier rendez-vous'),('Bonne destination','Mauvaise destination'),
('Animal de compagnie idéal','Pire animal de compagnie'),('Bonne odeur','Odeur insupportable'),
('Petite trahison','Grosse trahison'),('Dur à avouer','Facile à avouer'),('Optimiste','Pessimiste'),
('Plus drôle','Moins drôle'),('Écolo','Pollueur'),('Mauvaise habitude','Bonne habitude'),
('Bon méchant de film','Méchant raté'),
('Bonne pizza','Pizza honteuse'),('Bonne fête','Fête ratée'),('Repas léger','Repas qui cale'),
('Bon jeu de société','Jeu de société insupportable'),('Bien payé','Mal payé'),
('Facile à cuisiner','Difficile à cuisiner'),('Moment gênant','Moment glorieux'),
('Bonne compétence','Compétence inutile'),('Croustillant','Mou'),
('Énergie du lundi','Énergie du vendredi'),('Musique de premier rendez-vous','Musique d’enterrement'),
('Fait peur aux enfants','Fait peur aux adultes'),('Bonne garniture','Garniture immonde'),
('Tradition à garder','Tradition à abolir'),('Rêve d’enfant','Cauchemar d’enfant'),
('Bon parfum de glace','Parfum de glace bizarre'),('Fait vieux','Fait jeune'),
('Respectable','Louche'),('Bon pour la santé','Mauvais pour la santé')
on conflict do nothing;
