-- Priorités : un paquet de cartes propre au jeu, rangé par thème.
-- Le tirage puise dans les réponses du jeu à trou ET dans ce paquet ; le jeu
-- à trou, lui, ne voit jamais ces cartes (il ne lit que public.answers).
-- Les identifiants démarrent à 1 000 001 pour ne jamais croiser ceux des
-- réponses dans rooms.rank_cards.

create table if not exists public.priority_cards (
  id integer generated by default as identity (start with 1000001) primary key,
  text text not null,
  theme text not null default 'perso',
  added_by text,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);
create unique index if not exists priority_cards_text_uniq on public.priority_cards (lower(text));
alter table public.priority_cards enable row level security;
revoke all on table public.priority_cards from public, anon, authenticated;

-- cartes déjà tirées dans la salle (réponses et cartes Priorités confondues)
create table if not exists public.used_rank_cards (
  room_id uuid not null references public.rooms(id) on delete cascade,
  card_id integer not null,
  primary key (room_id, card_id)
);
alter table public.used_rank_cards enable row level security;
revoke all on table public.used_rank_cards from public, anon, authenticated;

-- Le paquet complet : chaque carte avec sa « famille ». Les réponses du jeu à
-- trou forment deux familles (verbes, noms), chaque thème en forme une.
create or replace function public._rank_pool(p_all boolean default false)
 returns table(id integer, text text, kind text) language sql stable security definer set search_path to '' as $function$
  select a.id, a.text, 'reponse-' || a.form from public.answers a where p_all or a.deleted_at is null
  union all
  select c.id, c.text, c.theme from public.priority_cards c where p_all or c.deleted_at is null
$function$;

-- Tirage : au plus une carte par famille, pour que les 5 cartes viennent de
-- registres différents (un joueur de foot contre un jour de la semaine…).
create or replace function public._draw_rank_cards(p_room uuid)
 returns integer[] language plpgsql security definer set search_path to '' as $function$
declare picked integer[];
begin
  if (select count(distinct p.kind) from public._rank_pool() p
      where not exists (select 1 from public.used_rank_cards u where u.room_id = p_room and u.card_id = p.id)) < 5 then
    delete from public.used_rank_cards where room_id = p_room;
  end if;

  with dispo as (
    select p.id, row_number() over (partition by p.kind order by random()) as rk
    from public._rank_pool() p
    where not exists (select 1 from public.used_rank_cards u where u.room_id = p_room and u.card_id = p.id)
  )
  select array_agg(x.id order by random()) into picked
  from (select d.id from dispo d order by (d.rk = 1) desc, random() limit 5) x;

  insert into public.used_rank_cards(room_id, card_id)
  select p_room, unnest(picked) on conflict do nothing;
  return picked;
end $function$;

revoke all on function public._rank_pool(boolean) from public, anon, authenticated;
revoke all on function public._draw_rank_cards(uuid) from public, anon, authenticated;
